### ISSUE TITLE
Backup Steam Cloud data

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#101]
Support to back up data from Steam Cloud.

This would need:
* Let user manually set path `*steamLibrary*`
* Specify Steam ID for games
* Checkbox for Steam Cloud support
* Rename `Monitor only` checkbox to `Backup save path`
* Backup succeeds if at least one save path is found in the system
* backups have subdirectories `regular/` `steam_*usersteamid*/`
* Backup from `*steamLibrary*/userdata/*usersteamid*/*gamesteamid*/remote/` for all users. (`*usersteamid*` is extracted from the path and used for the backup)

What yet has to get resolved:
* Theoretically steam allows multiple libraries (would ignore this fact)
* Dublicate include / exclude behavior for Steam Cloud backups
* Or use current settings for all backups

Either we hav many dublicates in our database or showing a folder for include / exclude will become tricky and we’d need to show tabs for all detected save paths
-> These problems occur in general when multiple save paths are allowed

This kinda reopens #92 in a different context

**Comment by MikeMaximus** [comment]
The [Custom Path Variables](http://mikemaximus.github.io/gbm-web/manual.html#customvariables)  feature was created to handle the Steam cloud save location and other similar situations.

That is about as far I want to go in directly supporting games that use a steam cloud save location.  I felt it's redundant to include Steam Cloud supported games in the official list.  But the options are there if the user wants to set it up themselves.
