### ISSUE TITLE
Please improve release naming

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#107]
Why has release v1.04 the file GBM.v1.0.4.32-bit.7z?

1.04 and 1.0.4 isn’t the same, please decide for one scheme and be consistent.
```sh
https://github.com/MikeMaximus/gbm/releases/download/v${pkgver}/GBM.v${pkgver}.32-bit.7z
```

**Comment by MikeMaximus** [comment]
A mistake that was just continued on because of how I build releases.  I will fix it next time, 1.04 is what it's supposed to be.
