### ISSUE TITLE
Store export date in XML file

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#109]
International date (`date +%F`)

```xml
<exported>
    2017-11-18
</exported>
```
or unix-style (`date +%s`)
```xml
<exported>
    1511039110
</exported>
```

This way the client can (automatically) check whether the game list got updated.

**Comment by MikeMaximus** [comment]
GBM will now include the exported date(unix) and the app version with the export.  Official game lists should be re-built with v1.05 at release so they use the new format.  Old XML files can still be imported, unless it's from prior to v0.94.

I'm not sure yet of how or if I'm going to implement an automatic game list check in the upcoming version.

gbm-web project will be updated so it can display the new list format and use the new export date field.

**Comment by MikeMaximus** [comment]
It's bothering me that the changes I made broke the ability for old versions to read the official import file.  I'm going to solve that problem and re-release v1.0.5.
