### ISSUE TITLE
[Feature request] Single instance mode

### ISSUE THREAD

**Issue by lazycrypt** [MikeMaximus/gbm#112]
Currently if you open GBM (either through shortcut or the executable directly) it will open a new process. Would it be possible to have an option to only ever have one single instance of the application running? Not only would this prevent possible conflicts it would also make opening the running application easier through a start menu shortcut rather than the system tray.

**Comment by MikeMaximus** [comment]
I had to disable single instance a while back so the "Restart as Admin" feature would work,  but I should have implemented another method to prevent multiple instances running at the same time.

In the upcoming version only one instance will be allowed.  GBM will show a message and close if it's already running.

**Comment by MikeMaximus** [comment]
Please note that this will be fixed for Windows only.  

I cannot find any method that works in Linux, even flipping Single Instance back on when compiling does not prevent multiple instances from running in Linux.

**Comment by MikeMaximus** [comment]
The fix for this isn't working as expected.  I've removed the v1.0.5 until I get this and another issue sorted.

**Comment by basxto** [comment]
You could write your own PID to `~/.local/share/gbm/pid` and if that file already exists check whether that process is still running, otherwise replace it.

**Comment by MikeMaximus** [comment]
Yeah that would work.  I did something similar with the initial fix, but it was buggy due to the method I used.

**Comment by MikeMaximus** [comment]
Mono is determined to screw this feature over.  I wrote a PID implementation worked fine in Windows, but in Linux it has trouble reliably checking if the process is running, sometimes it's GBM and sometimes it's mono-sgen.  And when it does work it won't reliably end the new process.  I'll spend a bit more time on this, but I may just have to shelve it again.

**Comment by basxto** [comment]
I can look into the start script, maybe I find a way to fix it there.

**Comment by basxto** [comment]
This does allow one gbm per user.
It does not bring the already running gbm session into foreground or so.
Theoretically it would be possible to send a signal (kill) from shell, GBM would need to catch that software interrupt and mark it’s window as urgent.
I don’t know if visual basic and mono can handle that.

**Comment by basxto** [comment]
That would look like this:
```
pkill -SIGUSR1 -F "${HOME}/.local/share/gbm/pid"
```
Currently GBM closes when it receives SIGUSR1

http://www.mono-project.com/docs/faq/technical/ (Can I use signal handlers with Mono?)

This was part of the original issue, but I don’t think this is necessary.
