### ISSUE TITLE
Provide Linux packages for installation

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#114]
We could provide debian and/or arch packages to install GBM.

Some information about this topic was already discussed in #113.

**Comment by basxto** [comment]
Haven’t noticed, that 1.0.5 got released.

**Comment by MikeMaximus** [comment]
Yeah I'll release 1.0.6 in the new year with some fixes + the Linux changes while i work on another branch with the 1.1 stuff.  Just wanted to make this an issue as a reminder next release.

**Comment by basxto** [comment]
First package: https://aur.archlinux.org/packages/gbm/
For building a real compressed package `PKGEXT=".pkg.tar"` would need to be removed.
But I think everybody installs from the AUR, it’s easy to update that way if you use a pacman-wrapper that can use AUR.

**Comment by MikeMaximus** [comment]
Thanks basxto.

So you'll take care of updating the AUR package when there is a new release?  That's fine with me whenever you have the time to do it.  

I'll get to testing the debian pull soon.

**Comment by MikeMaximus** [comment]
I'm trying to decide if I should provide two Debian packages, 32-bit and 64-bit.  I'll always provide a 32-bit Windows package since GBM may still be used on classic gaming rigs with Windows XP.  But I'm not sure the same situation exists with Linux gamers.  AFAIK running a 32-bit version of the OS is all but extinct in the Linux world.

So I'm thinking just one package with the 64-bit executable would be fine.

**Comment by basxto** [comment]
The package should work on both. I build the Archlinux package on top of the 32-bit version since it’s smaller. Does it even make a difference with .net? I thought the only difference is the 7za, you ship with GBM, but that is handled by the package manager.

I haven’t tested it, but I would expect GBM to even run on my ARM boards.

For 32-bit you usually have to have all 32-bit libraries installed. Especially games are often still 32-bit. Steam overlay itself is 32-bit.

**Comment by basxto** [comment]
I have disassembled both, I see no difference.

```terminal
monodis /tmp/gbm_test/32bit/GBM.exe > GBM.exe.32dis
monodis /tmp/gbm_test/64bit/GBM.exe > GBM.exe.64dis
diff -u GBM.exe.{32,64}dis > gbm.diff
```

The methods are off a few bytes, I got many differences like this one:
```diff
@@ -172,7 +173,7 @@
 
         .custom instance void class [System]System.ComponentModel.EditorBrowsableAttribute::'.ctor'(valuetype [System]System.ComponentModel.EditorBrowsableState) =  (01 00 02 00 00 00 00 00 ) // ........
 
-        // Method begins at RVA 0x2050
+        // Method begins at RVA 0x2048
 	.entrypoint
 	// Code size 22 (0x16)
 	.maxstack 8
```

I then removed those lines:

```terminal
sed -e "s|^.*// Method begins.*$||g" -i GBM.exe.32dis
sed -e "s|^.*// Method begins.*$||g" -i GBM.exe.64dis
```
And the only difference is this:

```diff
--- GBM.exe.32dis	2018-01-02 16:23:50.198013507 +0100
+++ GBM.exe.64dis	2018-01-02 16:23:53.784738659 +0100
@@ -97,7 +97,7 @@
 		6F 66 69 6C 65                                  ) // ofile
 
   .hash algorithm 0x00008004
-  .ver  1:0:5:19829
+  .ver  1:0:5:19827
 }
 .mresource public 'GBM.frmAdvancedImport.resources'
 {
@@ -147,8 +147,9 @@
 .mresource public 'GBM.Resources.resources'
 {
 }
-.module GBM.exe // GUID = {05F033BB-F4C9-47F3-B69F-170C2D61EAF9}
+.module GBM.exe // GUID = {C3572BB3-A159-481B-9922-C16A49400F0E}
 
+.stackreserve 0x400000
 
 .namespace GBM.My
 {
@@ -98139,7 +98140,7 @@
   {
     .custom instance void class [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::'.ctor'() =  (01 00 00 00 ) // ....
 
-    .field  assembly static initonly  valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=20' 40DD750866BB95B7678D207DC719A8954A161792 at D_00163380
+    .field  assembly static initonly  valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=20' 40DD750866BB95B7678D207DC719A8954A161792 at D_00163320
 
   .class nested private explicit ansi sealed '__StaticArrayInitTypeSize=20'
   	extends [mscorlib]System.ValueType
@@ -98518,6 +98519,6 @@
   } // end of class Shell32.ShellLinkObject
 }
 
-.data D_00163380 = bytearray (
+.data D_00163320 = bytearray (
 	 5C 00 2F 00 3A 00 2A 00 3F 00 22 00 3C 00 3E 00
 	 7C 00 2E 00) // size: 20
```

Both use int32, it shouldn’t make any difference.

**Comment by MikeMaximus** [comment]
The included 7za isn't the only difference, it actually is built for two different CPU targets.  With .NET I don't think the differences will be in the executable so much, it's mainly just a flag that tells the framework how to handle it.   

Ideally i'd just compile with the Any CPU target and release one package, but on Windows GBM can't access the details of 64-bit process unless it's own compile target is also 64-bit.  I've never actually tested if the 32-bit GBM running on Mono can detect a native 64-bit Linux process without throwing an exception.  But since you're using the 32-bit executable and haven't had an issue i'm thinking with Mono it doesn't matter.

**Comment by basxto** [comment]
Yes, linux does not seperate 32bit and 64bit. I can detect both kinds of games and that is definitely necessary.

`java32` `linux32` `trine2_linux_32bit` `Outland.bin.x86` `PonyIsland.x86` etc.

I suppose it’s not that mixed on windows. I think the x-fire plugin for pidgin (gfire) managed to track both kinds of processes on windows. They probably just ran two processes for that.

**Comment by MikeMaximus** [comment]
Alrighty, so I'll just build a single deb with the 32-bit executable.

Yeah there's other methods on Windows the x-fire plugin could be using that wouldn't have the same issue.  I like my current method since it works well in both .NET and Mono using nearly the same code.

**Comment by basxto** [comment]
I put gbm on watch, so I hopefully get notified now when a new tag gets added. So I guess, I can take care of all Linux packages in the long run.

Further plans I have:
* [ ] Improve makefile so that Debian/Ubuntu package can be built with regular user rights (`fakeroot`)
* [ ] Set up a user repository for that gbm package, this should just need a static webserver like gbm-web. (Automatic updates for Debian/Ubuntu)

I don’t expect (and hope) I won’t get that done anytime soon, since there is other stuff I should do first.

For Windows it’s maybe an option to add gbm to [chocolatey](https://chocolatey.org/) (uses NuGet)

**Comment by MikeMaximus** [comment]
Thanks, I just don't have any experience with Arch packages or repos.  I can build and test the deb when I do a release here though.  

A user repo would be great, but no rush or anything.  I appreciate any work you do when you can.  

Things may slow down a little more, I'm going into maintenance mode on the current branch of GBM and just planning on bug fixes only.  Anything new is getting pushed to 1.1 when I can get to it.

Chocolatey looks interesting, I'll check into it.
