### ISSUE TITLE
Session Viewer does not sort dates

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#117]
Dates get sorted like normal numbers, best sort by timestamps and not the displayed dates. Or enforce international big-endian `yyyy-mm-dd` format, but this could be irritating to some people.

Right now it looks like this: (using little-endian `dd.mm.yyyy`)
* 20.12.2017 19:40
* 20.**12**.2017 00:04
* 20.**11**.2017 03:16
* 20.11.2017 03:00
* 20.11.2017 02:22
* 19.**12**.2017 23:11
* 19.12.2017 22:12

With middle-endian `mm/dd/yyyy` format you’ll get that problem in a year.

Big-endian only became an accepted standard in Bhutan, Canada, China, Koreas, Taiwan, Hungary, Iran, Japan, Lithuania and Mongolia so far.
The majority of human population use little-endian.

**Comment by MikeMaximus** [comment]
I left it up to the control.  I'll have to apply manual routines to those columns so it works with all formats.

**Comment by MikeMaximus** [comment]
The form will now sort by unix time and not the display format.

**Comment by basxto** [comment]
This does not appear to be fixed in 1.0.6, I haven’t tested it back then.

But it goes like:

* 02.01.2018 17:43
* 02.12.2017 15:41
* 03.01.2018 16:27

**Comment by MikeMaximus** [comment]
Is it the initial sort that's broken? Does it work when re-sorted when you click the column header?

**Comment by MikeMaximus** [comment]
*sigh*, OK here's what happened.  

I fixed the bug initially, then a couple days later I restructured a bunch of the code on that form because it was sloppy, but ended up passing the wrong column variables to the sort function.  I didn't notice it was broken again on Windows because it sorts correctly there regardless.

Sorry about that.

**Comment by basxto** [comment]
Worse things happen. Like short-circuiting a prototype board, like I did today.

**Comment by MikeMaximus** [comment]
Ouch, well that's definitely worse!

I re-worked the sorting code yet again this morning, hopefully for the last time. Mono's version of the grid control is wonky with sorting and data types.  But it looks good now, current troubles are fixed and it's setup to easily handle new columns in the future.
