### ISSUE TITLE
Add "Hours" and "Total Hours" on Session Viewer

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#120]
I don't want to make the session viewer all that complex, but it currently doesn't give you a lot of useful information at a glance.

An "Hours" column would be nice to quickly see how long you spent playing the game that session,  instead of having to calculate it in your head.

A "Total Hours" would also be useful.  The total hours would be based on the current filter, so you can quickly see how much you've played a specific game or all games over the last week or month, etc.

**Comment by basxto** [comment]
I like the “total hours” 👍
