### ISSUE TITLE
Line endings in pre release

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#124]
The line endings for `gbm.sh` in the pre-release are still `\r\n` (Windows style) and not `\n` (Unix style)

Could you check if they are maybe right after doing:
```
rm gbm.sh makefile
git checkout -- gbm.sh makefile 
```

**Comment by MikeMaximus** [comment]
They still pulled with \r\n endings.  Maybe they need to be pushed again with \n and then they'll stay like that?

**Comment by basxto** [comment]
Maybe try a fresh clone? The last relevant commit was by me, so it must be `\n`. Otherwise `.gitattributes` does not work that way

**Comment by MikeMaximus** [comment]
I think I fixed it now by adding ``` eol=lf ``` for *.sh and makefile.  Works when I tested it in Windows, other files retain CRLF and makefile and sh are LF.
