### ISSUE TITLE
Optionally use libnotify on Linux

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#125]
Libnotify is a desktop-independant server-client way for showing notifications.

The last example is for VB.net: https://wiki.archlinux.org/index.php/Desktop_notifications#Usage_in_programming

Debian and Ubuntu know it as `libnotify0.4-cil`

I’m not sure how .net handles that. Can you it run with missing libraries if they are not used?

If there is no other way to make it optional, you could also use the console way:
```
$ notify-send --help
Usage:
  notify-send [OPTION?] <SUMMARY> [BODY] - create a notification

Help Options:
  -?, --help                        Show help options

Application Options:
  -u, --urgency=LEVEL               Specifies the urgency level (low, normal, critical).
  -t, --expire-time=TIME            Specifies the timeout in milliseconds at which to expire the notification.
  -a, --app-name=APP_NAME           Specifies the app name for the icon
  -i, --icon=ICON[,ICON...]         Specifies an icon filename or stock icon to display.
  -c, --category=TYPE[,TYPE...]     Specifies the notification category.
  -h, --hint=TYPE:NAME:VALUE        Specifies basic extra data to pass. Valid types are int, double, string and byte.
  -v, --version                     Version of the package.

```

**Comment by MikeMaximus** [comment]
Good idea, the default mono notifications are awful.  I don't want to add any library references that are only used on one OS, but the console method works just fine.  

I'll probably do another pre-release this afternoon or tomorrow with this included, just testing it now.

Reminders: Need to add libnotify-bin to deb control and notify-send to gbm.sh.

**Comment by basxto** [comment]
I would  make it an option in the settings and add notify-send as an optional dependency. The server also must be running. Not any, but most systems should support it.

You could check on program start with `whereis -b notify-send | cut -sd' ' -f2` whether it’s installed and grey the option out if it’s not. The rest will see it like it’s now.

**Comment by MikeMaximus** [comment]
We can make it an optional dependency.  Right now if it can't use notify-send it just sends a normal notification like before so I don't think we need a setting.  I should probably check the exit code as well and do a normal notification if it failed for another reason.

**Comment by basxto** [comment]
I would send it like this:
```
notify-send -a 'Game Backup Monitor' -i gbm -h string:desktop-entry:gbm 'Game Backup Monitor' '<i>Kingdom Rush Frontiers</i> detected'
```
I just tested it with awesome and lxqt, both do not support the desktop-entry hint.
Awesome only shows the icon if it’s a fixed path, but I think it’s better to let the implementation choose the icon size.

**Comment by MikeMaximus** [comment]
I'll change it to use default time and fix the icon size.  lxde must display it as a set size no matter what, I thought using the highest quality one would be best.   

It will recognize simply "gbm" for the icon?  The examples I seen were using a full path so I thought that's all it would take.

**Comment by basxto** [comment]
`-i gbm` worked for me in lxqt.

The [specification](https://developer.gnome.org/notification-spec/#icons-and-images-formats) says:
> The "app_icon" parameter and "image-path" hint should be either an URI (file:// is the only URI schema supported right now) or a name in a freedesktop.org-compliant icon theme (not a GTK+ stock ID).

This is also how I reference the icon in the `.desktop` file.

Since we installed it as a icon for the standard theme, it should work this way. It should be even possible to override it with a custom theme. I think, that is what gets done for popular applications.

**Comment by MikeMaximus** [comment]
It does work like that for me in lxde as well, I never tried it before.  We'll go with that then.

I've been passing it the -u argument as well based on if it's an error, warning or just a notification.  But I don't notice it doing anything differently,  i'm thinking about just dropping that.

**Comment by basxto** [comment]
Awesome shows `critical` in a persistent popup with red background. It’s up to the implementation.

**Comment by MikeMaximus** [comment]
Ok, I'll just leave then if some implementations are using it.
