### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by malitech** [MikeMaximus/gbm#132]
Hello,
Does this tool backup the save only when the game exits?
Can you make it backup saves every few minutes? I'm looking for this. For example, if a game crashes, the previous backup can be useful.

**Comment by basxto** [comment]
Backups are made when the game exits. There is also an option to backup manually trigger backups, but that’s of no help for you.
GBM can not store the current state of the game if that’s what you try to accomplish.
Does the savegame get corrupted when your game crashes?
What different behavior do you expect from just loading an old savegame?

**Comment by malitech** [comment]
Oh, why not? It can just make a backup every few minutes instead of creating it only when the game exits.
Yes. That's the point of making backups because if a game crashes, it may corrupt the save.
If the session continues for 5 hours and the game crashes and corrupts the save, it's useless backing up the corrupt save. If it however backs it up every few minutes like email drafts, it can be useful. We don't have to play all over again.

**Comment by MikeMaximus** [comment]
There are some reasons why I've never implemented a feature to backup saves while a game is running:

1.  If the game happens to be saving at the point GBM makes a backup, you're going to get a corrupted save as a backup.

2.  Some games will keep their saved game in an "open" state while playing and if it's copied while the game is running you end up with a backup that may not work if it's restored. 

3.  I haven't ran into a game so unstable that I've ever required this feature.

Game configurations in GBM can be setup to "Save multiple backups", this will keep multiple sessions to restore from if a problem occurs.  But even that feature, all I've ever used it for is save scumming. :godmode:

**Comment by malitech** [comment]
Oh I understand but you could enable the option with this warning so that users have a choice. It can be useful for many games. I once lost a whole game when the game crashed. Yesterday my game crashed but the saves were fine. I hadn't ended the session. And GBM didn't save it because of the crash. I uninstalled it because it's not useful for me. What I'm doing now is manually copying the folder and pasting it whenever I remember while playing the game.

**Comment by MikeMaximus** [comment]
That's odd, GBM will trigger a backup regardless of how the process ended, crashing or ended normally.  I can see how periodic backups while the game is running would be useful for some games and situations.  I'll see how much work it would be but can't make any promises.  Out of curiosity which game are you playing that crashes so often.

**Comment by malitech** [comment]
Oh thanks. :)
Assassin's Creed IV: Black Flag
I will be playing Unity next.
I don't know why it crashes sometimes. Maybe my gpu is bad.

**Comment by MikeMaximus** [comment]
A feature to periodically run a backup while the game is running would be useful in some situations, like when a certain game is crashing the entire OS or resetting the PC while you're playing.  But I've decided implementing this would require too many changes and too much re-testing for a feature that may be rarely used and have issues with some games.
