### ISSUE TITLE
Special savepaths for emulators

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#133]
For games running with an emulator, it would be interesting to specify savegames relative to the games location and not the emulator's.
The location could be extracted from the arguments.
It would also be necessary do the regex parameter wise, since `/home/dabascht/.local/share/lutris/runners/dosbox/bin/dosbox /home/dabascht/Games/star-wars-dark-forces/`is a legal directory name.
One could specify the matchgroup’s index with `\1`, where 0 is the regular match.
Or the relative path becomes relative to the first match if the “Extract location from process arguments” option is active.

Affected games so far:
* Star Wars: Dark Forces (lutris' DOSBox + Steam data)
  * process: `/home/dabascht/.local/share/lutris/runners/dosbox/bin/dosbox /home/dabascht/Games/star-wars-dark-forces/DARK.EXE -scaler normal3x -exit`
  * save file: `/home/dabascht/Games/star-wars-dark-forces/DARKPILO.CFG`
  * proposed regex: `(\/.+?\/)DARK.EXE`
  * proposed save path: `\1/DARKPILO.CFG`
* Duke Nukem 3D Atomic Edition (lutris' DOSBox + Steam data)
  * process: `/home/dabascht/.local/share/lutris/runners/dosbox/bin/dosbox -conf /home/dabascht/Games/duke-nukem-3d/Game/dosboxDuke3D_single.conf
-conf /home/dabascht/Games/duke-nukem-3d/Game/dosboxDuke3D.conf -scaler normal3x -exit`
  * save files: `/home/dabascht/Games/duke-nukem-3d/Game/data/`
  * proposed regex: `(\/.+?\/)dosboxDuke3D.conf`
  * proposed save path: `\1/data/`

**Comment by basxto** [comment]
GOG does not use absolute paths or paths relative to the DOSBox executable:

`/home/dabascht/Games/shadow-warrior/game/dosbox/dosbox_x86_64 -conf dosbox_swarrior.conf -conf dosbox_swarrior_single.conf -no-console -c exit`

The configuration file is located at `/home/dabascht/Games/shadow-warrior/game/dosbox_swarrior.conf`, therefore I would have expected `..\dosbox_swarrior.conf`.

**Comment by MikeMaximus** [comment]
GBM really should have better support for multiple games running from the same emulator binary.

I will look into this, but can't commit to it for next release yet.

**Comment by basxto** [comment]
I suppose finding a solution for this will take quite some time, if it is even solvable.
And it would need some understanding of DOSBox, I’m not sure if it will be used enough to be worth it.

**Comment by MikeMaximus** [comment]
Yeah it won't be easy, but I'll spend some time on it.  Ancient versions of GBM actually handled this better because it had dosbox specfic detection code, but it still couldn't detect a path relative to the game's DOS exe.

**Comment by basxto** [comment]
It would maybe be helpful to have variants of configurations.
Emulators, reimplementations and open source software is in general hard to track. They might have different executable names, different save places. It is so heterogenous it’s no fun.

Running Beneath a Steel Sky in native SCUMMVM it saves to `~/.scummvm/` and the exectable is  `/usr/bin/scummvm --extrapath=/usr/share/scummvm --themepath=/usr/share/scummvm --aspect-ratio --no-fullscreen --gfx-mode=3x --path=/usr/share/bass sky`.

Installing it via lutris the only difference is `--path=/home/dabascht/Games/beneath-a-steel-sky-lutris`

Running it with the version packaged by gog, it saves to `../data/` and the executable is `/home/dabascht/Games/beneath-a-steel-sky/game/scummvm/scummvm_x86_64 -c beneath.ini --themepath=scummvm`.

I don’t even know if the savegames are compatible.

For tracking it would be interesting to see all variants as one.

**Comment by basxto** [comment]
SCUMMVM is understandable, I guess.
It has:
* defaults
* command line options `-c`, `--config=` and `--savepath=` , last is always the game name (package manager, lutris)
* config file has ini format and supports `savepath=`, `gameid=` (gog)

Maybe there is a way to outsource emulator (including wine) logic into plugins.
Having some generic fields (some for storage and some for user configuration) and variables for them.
They get detected by process name.
They get process name and parameters from the process as well as from the configuration and do their magic.

Could be .net dll’s or own independent programs. Not sure about the possibilities here. For me that would be easier to build, test and contribute. Otherwise emulator code will just bloat GBM.

Plugins could be updated independently.

**Comment by MikeMaximus** [comment]
My next project should be more flexible in this regard, but I won't be making anymore changes to GBM to better support emulators.
