### ISSUE TITLE
Relative path save games

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#135]
When asking the user whether they want to overwrate a savegame, please mention it when the savegame comes from an relative origin.
Relative savegames are likely to be wiped when the game gets uninstalled.
Therefore there is a risk for also wiping the backup after reinstalling the game.

**Comment by MikeMaximus** [comment]
Just to clarify, you mean when GBM is attempting to overwrite the current backup and the saved games are from a relative location?

**Comment by basxto** [comment]
Yes, those located in the game's main directory.
These games are generally annoying.

Ideally one would restore savegames before playing.
It would be nice to detect freshly installed games and restore backups, but GBM can’t do that. Even with game managers that would only work if you don’t install games externally.
