### ISSUE TITLE
Detects zombie processes as running

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#137]
GBM detects [zombie processes](https://en.wikipedia.org/wiki/Zombie_process) as “running”

```shell
$ ps ax | grep game-bin
 3789 pts/1    S+     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn game-bin
29187 ?        Z      0:07 [game-bin] <defunct> 
```

**Comment by MikeMaximus** [comment]
I can possibly check the exit code of the process to easily see if its a zombie without bogging down the detection code with an external call.

**Comment by MikeMaximus** [comment]
I used some C code to create a zombie process to do some testing, and as far as I can tell there's no way to determine if a process is a zombie using the tools in .NET / Mono.  I'd need to make an external call to ps on every detection.

How big of an issue is this?  Doesn't the OS periodically clean up zombies?  If they're only running a certain amount of time the "Ignore sessions shorter than X" setting would prevent GBM from doing anything beyond detection.

**Comment by basxto** [comment]
I have to close the parent application for the zombie to vanish.

This can go unnoticed, since the game window closed. 
A tray icon would make it easier to notice, but that also doesn’t work.

I guess, it can be helped them.

**Comment by MikeMaximus** [comment]
It doesn't seem to be much of an issue to check for this with ps.  When you get a chance try this build and see if it works in your situation too.

https://www.dropbox.com/s/chi38383m8mrhi7/GBM.7z?dl=0

There's been no database changes since 1.1 so you can try it and revert back without messing with your data.

**Comment by basxto** [comment]
No, that does not help.
But I noticed that lutris removes the zombie when I start a new game.

This is probably something that should rather be fixed in lutris, since it can produce a zombie when you push the “stop game” button.

**Comment by MikeMaximus** [comment]
So you start a game from Lutris, GBM detects it, then you click stop, the process becomes a zombie and GBM still thinks its running? If thats the case what I implemented won't do anything, that would need much bigger changes.  But yeah they should probably fix that in Lutris.

**Comment by basxto** [comment]
Yes.
But Guacamelee (game-bin) is the only game so far, I’ve seen becoming a zombie in lutris.

**Comment by MikeMaximus** [comment]
Reminds me I need to finish Guacamelee.  I loved that game but got distracted and never went back to it.  

I'll close this issue for now.  I can fix it if I start polling the process periodically after it's detected to make sure it's not a zombie, in addition to the detection change.  But it's a bit much for the issue severity.
