### ISSUE TITLE
Allow infinite backups

### ISSUE THREAD

**Issue by Gantzyo** [MikeMaximus/gbm#138]
Why not allow an unlimited number of backups? 
It would be great if we can set Save multiple backups + 0 backup limit = unlimited number of backups.
This way we can manually manage them.

**Comment by MikeMaximus** [comment]
I'll include this with some other enhancements I've wanted to make to multiple backups.

Some other changes I want to make (this is mostly so I don't forget when I get around to it):

1.  The ability for GBM to know when you've deleted backups manually and update it's manifest.
2.  The ability to restore any backup selected on the Game Manager, currently the latest one is always restored regardless of what's selected, which isn't really explained and counter-intuitive.

**Comment by MikeMaximus** [comment]
This is ready for next release.
