### ISSUE TITLE
Include items not always greyed out

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#139]
Disabling `Monitor only` ungreys `Include Items…` even if `Save entire folder` is enabled.

This leads to some weird behavior:

* Select some items for inclusion and save
* Close and reopen game manager
* Go back to the game and disable `Save entire folder` -> still shows correct amount of items
* Click `Include Items…` -> list is  empty
* Click `Save` or `Cancel` ->  amount gets updated

**Comment by MikeMaximus** [comment]
Thanks,  looks like there was some other issues in that function I fixed as well.
