### ISSUE TITLE
Tell detected process name

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#141]
I played some games the night, one didn’t close properly.
GBM just tells me “Mutliple Games Detected”, there is no way of finding out which game is blocking gbm.

This could also be helpful with detecting false positives for games with such stupid process names as:
* `linux_client`
* `runner` (only one with multiples so far)
* `linux32`
* `linux.x86`
* `bin64.sh`

**Comment by MikeMaximus** [comment]
Yeah that would be useful.  

It will now show the full path of the process when multiple configurations are triggered.
