### ISSUE TITLE
Drag and drop import for linux

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#143]
FreeDesktop.org's specifications is what is widely used.
The biggest desktop environments KDE and Gnome support it.
Many of the smaller ones also do.

Dragging an icon from the desktop to GBM should offer the `.desktop`-file.

Specification for the ini-like `.desktop` files:
https://specifications.freedesktop.org/desktop-entry-spec/1.2/
Particularly the list of used keys: https://specifications.freedesktop.org/desktop-entry-spec/1.2/ar01s06.html
`Name`, `Comment` (rather a description), `Icon`, `Exec`, `Path` (working directory)

Icons can be an absolute path or the name of an installed icon, installed icons are described here:
https://specifications.freedesktop.org/icon-theme-spec/0.13/
Particularly the pseudocode for looking up icons: https://specifications.freedesktop.org/icon-theme-spec/0.13/ar01s05.html
This system is more flexible than on windows, since icon themes can override icons that get shipped with the application.
Paths are variable and can be changed by the administrator/user with environment variables defined in the [basedir specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). I don’t know if GBM already follows that specification, I suspect not.
> The supported image file formats are PNG, XPM and SVG.

And exec also can be either an absolute path or a name of an installed executable. Running it with a subshell should be enough and the best solution, by default they search in all valid bin-directories. The string can include parameters.
This is not in all circumstances suitable for detection

Name and comments can be localized like this excerpt of a gnome game:
```
Name=SameGame
Name[be]=Гульня Same
Name[bn]=সেইমগেম
Name[br]=Heñvelded
Name[bs]=SameGame
Name[ca]=Joc iguals
GenericName=Board Game
GenericName[af]=Bord Speletjie
GenericName[be]=Настольная гульня
GenericName[bn]=ছককেন্দ্রিক খেলা
GenericName[br]=Ur c'hoari taolenn
GenericName[bs]=Igra na ploči
```

Following two examples of desktop files:

Created on my desktop by the gog installer, it has absolute paths for the game executable and icon
```
[Desktop Entry]
Encoding=UTF-8
Value=1.0
Type=Application
Name=Punch Club
GenericName=Punch Club
Comment=Punch Club
Icon=/home/dabascht/gog_games/Punch Club/support/icon.png
Exec="/home/dabascht/gog_games/Punch Club/start.sh" ""
Categories=Game;
Path=/home/dabascht/gog_games/Punch Club
```

Created by steam, it runs steam with parameters to start the game and uses an icon installed for the user.
```
[Desktop Entry]
Name=PixelJunk™ Shooter
Comment=Play this game on Steam
Exec=steam steam://rungameid/255870
Icon=steam_icon_255870
Terminal=false
Type=Application
Categories=Game;
```
Installed with my package manager, this uses globally installed executable and icon:
```
[Desktop Entry]
Version=1.0
Name=0 A.D.
Exec=0ad
Icon=0ad
Terminal=false
MimeType=application/x-pyromod+zip;
Type=Application
Categories=Game;StrategyGame;
Comment=A real-time strategy game of ancient warfare
Comment[de]=Ein Echtzeitstrategiespiel, das die Kriegsführung der Antike behandelt
Comment[es]=Un juego de estrategia en tiempo real de guerra antigua
Comment[fr]=Un jeu de statégie militaire en temps réel dans l'Antiquité
Comment[it]=Videogioco strategico in tempo reale di guerre antiche
Comment[nl]=Een real-time strategie spel over oorlog van de oudheid
Comment[pl]=Gra strategiczna czasu rzeczywistego  o wojnach starożytnych
Comment[pt_BR]=Um jogo em tempo real de guerra antiga
Comment[ru]=Игра в жанре исторической стратегии в реальном времени
Keywords=RTS;Realtime Strategy;Economic Simulation Game;History;Warfare;Infantry;Cavalry;Siege Engines;Fortress;Celtics;Hellenes;Athenians;Britons;Carthaginians;Gauls;Iberians;Macedonians;Mauryans;Persians;Ptolemies;Romans;Seleucids;Spartans;
Actions=Atlas;

[Desktop Action Atlas]
Name=Atlas Map Editor
Exec=0ad -editor
```
---
Starting a branch with a stub that accepts `.desktop`-files and adds a game with hard coded data might be a way to go. I could then try to fill in the parsing and directory lookup.

**Comment by MikeMaximus** [comment]
This may be doable, but there are going to be some issues.  We can't get the game process to monitor from Steam desktop files since it's using Steam to launch.  Nor from games that use shell scripts to launch, unless we also parse the script to look for it,  but that would also be problematic.

**Comment by basxto** [comment]
Many cases should work.
I wouldn’t try to detect more complex cases
I’m not sure how much this would help people who are not tech savvy.
It makes it at least easier to get started with gbm.

Steam games are in general problematic.

**Comment by MikeMaximus** [comment]
I was thinking about this issue again for v1.1.8.  It's a good idea, but it just seems the amount of work involved greatly outweighs the benefits.  Linux users are generally power users who would be working directly with the Game Manager instead of the Add Game Wizard anyway.

**Comment by basxto** [comment]
Yes, many of my issues are of a far too theoretical nature.

**Comment by MikeMaximus** [comment]
I like your theoretical issues.  I usually learn new things even if they end up being too much work or beyond my abilities.
