### ISSUE TITLE
Unexpected Error - string cannot be of zero length

### ISSUE THREAD

**Issue by FoxThorne** [MikeMaximus/gbm#144]
Suddenly today getting this error when trying to launch GBM. Both x32 or x64 provide the same error.
Has been working flawlessly up till today, nothing changed on my system; not even a Windows Update.

Any ideas? Thank.

![5ybmdo](https://user-images.githubusercontent.com/40448036/43055323-b509f398-8dfb-11e8-9f74-65862962eed7.jpg)

**Comment by MikeMaximus** [comment]
My guess is one of GBM's databases was damaged.

You can try the following.

1.  If you're using GBM v1.1 or higher,  you can try to restore the automatic backups from the last time GBM successfully started.
- Rename your current gbm.s3db files to gbm.s3db.current.  They are located in C:\Users\Your User Name\AppData\Local\gbm and the backup folder you specified in GBM.
- Rename C:\Users\Your User Name\AppData\Local\gbm\gbm.s3db.launch.bak to gbm.s3db. 
- In your backup folder, rename gbm.s3db.launch.bak to gbm.s3db.
- Try to start GBM.

2.  If you're using an older version of GBM or the above doesn't help.
-  Rename C:\Users\Your User Name\AppData\Local\gbm to C:\Users\Your User Name\AppData\Local\gbm1 then see if it starts up.  This essentially resets GBM, but if you point it at your backup folder, it will restore your prior configurations, if the backup folder database wasn't damaged as well.

If the above helps, I'd like to take a look at the database files that are causing the error.   You can attach them to this issue.

**Comment by PersonalProxy** [comment]
Tried this just tonight (sorry, long day). Unfortunately, step 1 results in the exact same error.
Step 2 allow the program to run, with the "First use wizard" popping up, but as soon as I click anything I receive what looks like a .[NET error, seen here.](https://pastebin.com/xC6wycMQ)

I've attached both files from both folders so you can investigate should you like too.
[AppData-gbm.zip](https://github.com/MikeMaximus/gbm/files/2221720/AppData-gbm.zip)
[BackFolder-gbm.zip](https://github.com/MikeMaximus/gbm/files/2221721/BackFolder-gbm.zip)

After those steps, I went ahead and just completely uninstalled the app, removed all of the AppData and BackupDir files, reinstalled and relaunched, what I am met with at this point is the app appears to function normally.. except if I try to import the master game list from the web; then I get the exact same error I linked above.

I tried reinstalling .NET to see if that was the issue, but no dice.
Thanks for your help, let me know if I can provide anything more helpful.

**Comment by MikeMaximus** [comment]
Thanks for the information.  The database files are fine.  

Judging by the new error message,  it's crashing because one of the environment path variables GBM needs is being returned as empty, for example the location of your Documents or AppData folder.  I can't tell which one specifically based on the error message.

It's very strange this just started happening out of the blue.  Which version of Windows are you using?

**Comment by MikeMaximus** [comment]
I looked into the code this morning, and logically this error shouldn't ever be able to occur.  I can't even force it to occur by supplying bad data, which makes me think something weird is happening at the .NET level.  

I'd also like to know which version(s) of the .NET framework are installed on your system.

**Comment by PersonalProxy** [comment]
**Windows 10, v.1803 (OS Build 17134.167)
.NET v.4.7.03056**

My AppData folder is where it normally is, but when I setup my PC I did move my "Documents" folder to a secondary hard-drive, via the explorer properties window: 
![ud6orw](https://user-images.githubusercontent.com/40448036/43145935-add9b95c-8f25-11e8-8134-bdad14604bcd.jpg)

My "Backup Folder" in GBM settings is set to the same drive however: "D:\Backups\PC Games" and I use rSync to automatically backup the data in that directory to my personal cloud.

Even moving the Documents folder back to it's original location results in the same error.

**Comment by MikeMaximus** [comment]
Those are the exact versions i'm using, so that should be ok.

Yeah I don't think it's a problem with the environment path(s) anymore after looking at the code this morning, since even manually supplying empty data to that function doesn't make it crash.  And I assume GBM was working with that alternate documents path before this started happening.

I'm not sure what else to try.  Have you tried an alternate backup folder that isn't being monitored by rsync?

Maybe I can get a custom build for you that can better pinpoint where the error is occuring.

**Comment by MikeMaximus** [comment]
I've built a new version that cleans up the function where the error is being thrown,  as well as added some verification for environment paths when the application launches.  I just want to completely rule out any issues with environment paths.

Please try this build [GBM.zip](https://github.com/MikeMaximus/gbm/files/2225144/GBM.zip) when you have time.

Rename your current GBM.exe to GBM.bak and extract the one in the zip to the installation folder.

Let me know if it helps or a new error occurs.  Thanks.

**Comment by PersonalProxy** [comment]
Ok, went ahead and downloaded the zip.
Just FYI Windows Defender throws up a virus warning: https://i.snag.gy/FhKgoE.jpg

Anyway, with the new .exe everything seems to be working just fine so far.
No errors, and backups are occurring as they should. Thank you very much!

**Comment by MikeMaximus** [comment]
Hmm I'm not sure about the trojan warning.  I compiled it on the same machine I do most releases with and tested clean here.  

I'm glad it's working now!  I was just taking a wild stab at what might be causing it to fail for you.  I'm still curious why it just started doing that out of nowhere though.

You can continue using that build and the next release will include those changes.
