### ISSUE TITLE
AUR makepkg failure 

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#146]
Building the gbm package from the AUR currently fails, for me anyway.  

```
[mike@arch-vbox gbm]$ makepkg
==> Making package: gbm 1.1.3-1 (Thu 23 Aug 2018 08:42:26 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found GBM.v1.1.3.32-bit.7z
==> Validating source files with sha256sums...
    GBM.v1.1.3.32-bit.7z ... Passed
==> Extracting sources...
  -> Extracting GBM.v1.1.3.32-bit.7z with bsdtar
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
make: Entering directory '/home/mike/Downloads/gbm/src'
convert 'gbm.ico[7]' 'gbm_24x24.png';
convert: subimage specification returns no images `gbm.ico' @ error/constitute.c/ReadImage/629.
make: *** [makefile:49: gbm_24x24.png] Error 1
make: Leaving directory '/home/mike/Downloads/gbm/src'
==> ERROR: A failure occurred in package().
    Aborting...
```

The failure doesn't make any sense to me since the ico hasn't changed and it should contain that image size at the layer it's requesting.

@basxto Any ideas?

**Comment by basxto** [comment]
I will update to newest imagemagick and see if I can reproduce.

```
$ pacman -Qi imagemagick
Name                     : imagemagick
Version                  : 7.0.8.7-1
```

My system is a bit outdated.

```
$ cd src
$ convert 'gbm.ico[7]' 'gbm_24x24.png'
```
works here

**Comment by MikeMaximus** [comment]
This is the version on my system.

```
[mike@arch-vbox src]$ pacman -Qi imagemagick
Name            : imagemagick
Version         : 7.0.8.10-2
```

Fails out, but oddly the command is successful and the 24x24 png is in the folder.

```
[mike@arch-vbox src]$ convert 'gbm.ico[7]' 'gbm_24x24.png'
convert: subimage specification returns no images `gbm.ico' @ error/constitute.c/ReadImage/629.
```

**Comment by MikeMaximus** [comment]
I'll close this since it seems to be related to a problem beyond our control.

**Comment by basxto** [comment]
Now I can reproduce that.

It is something, I have to fix. Worst case would be to just ship the PNGs with the release package / put them into the repository.

**Comment by MikeMaximus** [comment]
Ah ok.  I thought it may have been a temporary issue with imagemagick that would be fixed.

**Comment by basxto** [comment]
Imagemagick dislikes the format if the icon.
It looks like it violates a specification, but imagemagick still extracts the image.

I repackaged the .ico-file , but that doubled the size. 
Gimp can create icons smaller in size, but that again leads to the error.

Did you create the icon with gimp?

**Comment by MikeMaximus** [comment]
Yes it was created in GIMP.

**Comment by MikeMaximus** [comment]
The 256x256 layer is compressed,  which does break spec.  I re-exported the ico without compression and imagemagick has no problem with it.  I'll update the ico.

**Comment by MikeMaximus** [comment]
Thanks for looking into this.  I guess it'll be broke for a little while, but i'll get 1.14 out in a day or two.
