### ISSUE TITLE
Add "Import Backup" option to Game Manager

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#150]
Add the ability to choose one or more 7z files to import into GBM's manifest.

1.  Add "Import Backup" to Game Manager.  Accept 7z files.  Multi-Select.
2.  If they're not there already, copy the files to the GBM backup folder.
3.  Rename files using same naming scheme as "Save Multiple Backups".  Maybe also add "import" to the name.
4.   Generate Manifest entries for each backup.  Use Date Modified of the file and current system name.

GBM will not verify the imported files,  it's relying on the user to ensure they've selected the correct files for the game.

I mainly want this as a quick way to import my Linux backups onto my Windows system and vice versa, but it has other uses.  Like if you lost your GBM database files, but still had the backup files.

**Comment by basxto** [comment]
Including a small xml file in the archive could also help.
The ID would be all one needs, but I would prefix it with `L` for Linux and `W` for windows and wine.
Timestamp, original path, computer name, GBM version could also be interesting.

Importing L-Backups into Windows wouldn’t be possible, savegames aren’t necessarily compatible between different versions and platforms. Some linux builds are outdated.

Maybe `_gbm_gamesave_metadata.xml`, that shouldn’t collide with any savegames. Or moving everything else to a subfolder `savegame`.

**Comment by MikeMaximus** [comment]
I like the XML idea,  maybe something for future once I get the framework for this done.

You can moved saved games between Linux and Windows if the game is Unity engine based and the same version, I've never had an issue with it anyway.  But yeah native ports like the ones from Aspyr or Feral likely wouldn't be compatible with the Windows counter-part.

**Comment by basxto** [comment]
[Some Unity games](https://pcgamingwiki.com/wiki/AaaaaAAaaaAAAaaAAAAaAAAAA!!!_for_the_Awesome) [store](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html) their savegames in the windows registry.
On Linux that gets written to `~/.config/unity3d/${developer}/${game}/prefs`.
I wrote an issue for that, but forgot to submit it.

Problem with importing L-Backups would also be, that Windows list and Linux list use different IDs.

**Comment by MikeMaximus** [comment]
Right, I never did get around to implementing registry key backups, I haven't played many that do so it was never a priority.  Actually the only game I can recall is Volgarr the Viking in Windows.  It wouldn't be that difficult, more of a pain in the ass with GUI and validation changes than anything else.

My current plan is to first allow importing backups to one game at a time and it's up to the user to make sure it's a backup file compatible with said game.  But once XML identifiers are part of the backups, and allowing a mass import of files that would become an issue.
