### ISSUE TITLE
Support saves in registry

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#151]
[Some Unity games](https://pcgamingwiki.com/wiki/AaaaaAAaaaAAAaaAAAAaAAAAA!!!_for_the_Awesome) [store](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html) their savegames in the windows registry.

In wine they just end up in the registry file.

On windows it should be [straight forward](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/programming/computer-resources/how-to-read-a-value-from-a-registry-key)

I would just input registry keys as a “Path”, they appear to always start with “HKEY_”
`Include Items…` and `Exclude Items…` would behave different, but look the same.
The registry has a folder-like structure after all.

**Comment by MikeMaximus** [comment]
I've been pondering the best way to do this:

**1.  Write my own registry manager to create and read/process either a standard registry export file or a similar custom format.**

Pros:
- Powerful, can use includes/excludes to customize exactly which values in a key and/or subkeys should be saved
- Include / Exclude builder could allow you to browse the registry the same as a folder structure

Cons:
- Large amount of time to implement and test
- Windows / Wine would require their own unique code paths, one manipulates the Windows registry and the other to parse and edit a Wine registry text file
- Potentially dangerous (in Windows) if bugs occur

**2.  Use regedit (command line) to handle everything related to the registry**

Pros:
- Much smaller amount of time to implement and test
- The use of a mature utiltiy that exists by default in all current versions of Windows and Wine prefixes.
- Very similar code can be used for both Windows and Wine to handle backup and restores.

Cons:
- Regedit can only export/import an entire key, includes/excludes could be implemented by manipulating the export file after it's created by regedit.
- Also potentially dangerous (in Windows) if used for nefarious purposes.

**Comment by basxto** [comment]
Wine’s regedit only allows to export (`-E`) and delete (`-D`) keys. According to the man page every other option is either ignored or unimplemented.

**Comment by MikeMaximus** [comment]
Hmm, according to https://wiki.winehq.org/Regedit it has the features I'd need.  

It runs in silent mode by default, it exports with -E and without any switches it imports the contents of a .reg file.  I'll need to test it before I decide on anything.

**Comment by MikeMaximus** [comment]
Reminders for myself before releasing v.1.1.8:

- Make the registry path check case-insensitive
- Check if hive shortcuts (HKCU and HKLM) work
