### ISSUE TITLE
Problem detecting games with similar executables

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#153]
`Kingdom: Classic` with `Kingdom.x86` gets detected.
`Kingdom: New Lands` with `Kingdom\.x86(_64)?` gets not detected.
I  can detect New Lands when I limit it to `Kingdom.x86_64`, though.

**Comment by MikeMaximus** [comment]
I'll try to look into this soon, does it work if you end the regex with an end of string character?

Kingdom\.x86(_64)?$

**Comment by MikeMaximus** [comment]
Replicated this,  not sure what's going on yet.

**Comment by MikeMaximus** [comment]
I believe I got this fixed now.  There was multiple issues with configuration load order and duplicate handling.

The Kingdom: New Lands configuration will detect both Kingdom: Classic and Kingdom: New Lands initially,  but after the user chooses what they were playing GBM will detect them automatically based on their path.

**Comment by basxto** [comment]
`$` does not help.
When I remove Kingdom: Classic, the regex Kingdom: New Lands works.
When I run Kingdom: Classic, I also don’t get window for game selection.

Okay, I will look at the code then. I’m building a small testprogramm locally.

**Comment by MikeMaximus** [comment]
I decided i'm going to tackle rewriting detection before I continue with anything else, because it's likely going to have an effect on other areas I need to change.

**Comment by MikeMaximus** [comment]
I rewrote how duplicates are handled and some of the detection code, which should resolve the problems with regex. It also handles detection by parameter and process path more a bit more efficiently now.  

I wanted to do more, such as being able to detect and handle multiple running configurations, but it just got out of control and I had to revert it.  I want to get to work on other issues, like the path variables.

**Comment by basxto** [comment]
I actively do not support detecting multiple processes in my project:
* You can reduce overhead while playing by waiting for the process
* It is unlikely that one plays mutliple games at the same time

**Comment by MikeMaximus** [comment]
Yeah that's true, it would be a pretty useless feature to spend a lot of time on.

**Comment by basxto** [comment]
I guess it would be mostly this:
* Keeping a list of all tracked PIDs
* Filter out already tracked PIDs while scanning
* Creating a thread for each detected game and add pid to list
  * Do a `waitOnExit`
  * Report back to main thread
* Remove game from list
* Create Session object
* Start backup also in new thread, so it does not block the scanning
