### ISSUE TITLE
Problems with recursive backups

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#160]
I’m having quite some trouble with backupping this path: `/home/dabascht/.barrage.hscr`
```
[08.10.2018 07:39:17] A manual backup of Barrage was triggered.
[08.10.2018 07:43:19] Available Disk Space: 10,17 GB
[08.10.2018 07:43:19] Barrage Save Folder Size: 172 B
[08.10.2018 07:43:19] Backup of /home/dabascht/ in progress...

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz (306A9),ASM,AES-NI)

Scanning the drive:
[08.10.2018 07:43:19] Barrage backup failed due to an error.
```
7z goes through my whole home directory of 480GiB.
GBM just freezes while it’s doing that.

----

GBM calls 7z like this, right?

`7za a -t7z -mx5 -i@/home/dabascht/.local/share/gbm/gbm_include.txt -x@/home/dabascht/.local/share/gbm/gbm_exclude.txt ~/game_backup_monitor/savegames/Barrage/Barrage.7z -r `

With `gbm_include.txt`  just containing this:
```
"/home/dabascht//.barrage.hscr"

```

I’m trying to reproduce it on command line and try to maybe find a work around.

**Comment by basxto** [comment]
This is likely #84 again

**Comment by basxto** [comment]
Okay, 7za had some permission issues with one file. Without `-r` that wouldn’t have  mattered.
And I noticed that GBM takes much longer than running 7za in the terminal.

Do we really need `-r`? Doing stuff like `*/*.sav` might  be faster.
Finding configurations, wo depend on it, would be a lot of work, though.

**Comment by MikeMaximus** [comment]
GBM takes much longer because it also scans the whole folder before 7z does to determine backup size.

Maybe the cleanest way to solve problems with this type of configuration is to add a new option (per config) to disable recursion.  This option would remove -r from the 7z command and prevent GBM from reading sub-directories when doing it's scan.

**Comment by basxto** [comment]
Since GBM already found all files, you could theoretically write their true paths into the include /exclude files and run 7za  without -r. This would also reveal when GBM misses some files. Does GBM handle * recursively?

**Comment by basxto** [comment]
I don’t even understand, how this is working.
For Borderlands 2 I used:
Save Path: `/home/dabascht/.local/share/aspyr-media/borderlands 2/willowgame/savedata`
Include Items: `profile.bin:*.sav`
Resulting gbm_include.txt:
```
"/home/dabascht/.local/share/aspyr-media/borderlands 2/willowgame/savedata/profile.bin"                                                                       
"/home/dabascht/.local/share/aspyr-media/borderlands 2/willowgame/savedata/*.sav"
```

It matches:
```
/home/dabascht/.local/share/aspyr-media/borderlands 2/willowgame/savedata/76561198025882370/profile.bin
/home/dabascht/.local/share/aspyr-media/borderlands 2/willowgame/savedata/76561198025882370/save0001.sav
```
That is what I wanted it to do, but reading the gbm_include.txt file I would not expect it to match the profile.bin

**Comment by MikeMaximus** [comment]
I'm not sure if the documentation available for 7za is up to date, because * and -r have always worked the way I've expected them to.  I tested * and it did include files that begin with a dot, even with the ancient 9.2 version in my VM.

> That is what I wanted it to do, but reading the gbm_include.txt file I would not expect it to match the profile.bin

I think when -r is used it takes the filename/pattern at the end of the path and also matches it against any sub-folders/files.  It is a bit weird.

**Comment by MikeMaximus** [comment]
> Since GBM already found all files, you could theoretically write their true paths into the include / exclude files and run 7za without -r.  This would also reveal when GBM misses some files. Does GBM handle * recursively?

Yes that could be a good method to get away from using -r.  GBM currently always recurses into sub-folders when doing a scan.

**Comment by basxto** [comment]
Yes, they are wrong about *, I tested it. `subfolder2/*` also included the dot file.
> I think when -r is used it takes the filename/pattern at the end of the path and also matches it against any sub-folders/files. It is a bit weird.

That is why they’ve a warning in the man page, I think.

-----
And I made a further test:

Working directory is `/tmp/gbmtest` and used comand is `7za a -t7z -mx5 -i@test_include.txt  test.7z -r`
Folder structure looks like:
```
tree -a                                                                                                                       
.                                                                                                                                                             
├── 1.txt                                                                                                                                                     
├── 2.txt                                                                                                                                                     
├── .4.txt                                                                                                                                                    
├── subfolder                                                                                                                                                 
│   ├── 1.txt                                                                                                                                                 
│   ├── 3.txt                                                                                                                                                 
│   └── subsub                                                                                                                                                
│       └── 1.txt                                                                                                                                             
├── subfolder2                                                                                                                                                
│   ├── 1                                                                                                                                                     
│   ├── 2                                                                                                                                                     
│   ├── 3                                                                                                                                                     
│   └── .5                                                                                                                                                    
├── test.7z                                                                                                                                                   
└── test_include.txt                                                                                                                                          
                                                                                                                                                              
3 directories, 12 files 
```

`subfolder/1.txt` gives:
```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2018-10-09 00:35:58 ....A            0            0  subfolder/subsub/1.txt
2018-10-08 20:34:47 ....A            5            9  subfolder/1.txt
------------------- ----- ------------ ------------  ------------------------
2018-10-09 00:35:58                  5            9  2 files
```

`/tmp/gbmtest/subfolder/1.txt` gives:
```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2018-10-09 00:35:58 ....A            0            0  subsub/1.txt
2018-10-08 20:34:47 ....A            5            9  1.txt
------------------- ----- ------------ ------------  ------------------------
2018-10-09 00:35:58                  5            9  2 files
```

This means if you resolve the place holders with GBM, you should give 7za relative paths and not absolute paths like you do now. The backup would work fine, but the restore would fail.

**Comment by MikeMaximus** [comment]
I'm still leaning towards adding an "Include Sub-Folders" option for configurations to allow disabling recursion when it isn't needed.  It's the least disruptive change that helps with this issue and leaves me more time to work on other features.

**Comment by basxto** [comment]
Yes. It would break configurations otherwise.

**Comment by MikeMaximus** [comment]
I've made the following changes for this issue:

1.  Added a "Recurse sub-folders" option.  This enables or disables -r on the 7za command and modifies GBM's behavior when determining folder size.
- This option defaults to enabled on all existing configurations.
- This option defaults to enabled on all new configurations.
- This option can be enabled or disabled on the "Include/Exclude" builder form.  I think that is where it makes most sense, as that is what -r has a direct effect upon.  I think it would be confusing to most users on the base Game Manager form.

2.  GBM now mirrors 7-Zip's recursion behavior when doing folder size calculations.
- When "Recurse sub-folders" is enabled, every sub-folder of the save path is going to be scanned.
- When "Recurse sub-folders" is disabled, only sub-folders that are part of the includes will be scanned.
- I also fixed some other bugs with the folder size calculation function that may have been causing problems.

**Comment by basxto** [comment]
It does not appear to work properly.
Save Path: `~/`
Include Items…: `.warzone2100-*/savegames` `[ ] recurse sub-folders`

7zip has permission issues with files, it shouldn’t even touch.

Output:
(Keine Berechtigung = no permission)
```
[22.01.2019 11:02:44] Warzone 2100 Detected
[22.01.2019 11:03:02] Warzone 2100 has ended.
[22.01.2019 11:03:02] Available Disk Space: 107,73 GB
[22.01.2019 11:03:02] Warzone 2100 Save Folder Size: 0 B
[22.01.2019 11:03:04] Backup of /home/dabascht/ in progress...

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz (306A9),ASM,AES-NI)

Scanning the drive:
10 folders, 88 files, 1663450 bytes (1625 KiB)

Creating archive: /home/dabascht/game_backup_monitor/savegames/Warzone 2100/Warzone 2100.7z

Items to compress: 98


Files read from disk: 85
Archive size: 104968 bytes (103 KiB)

Scan WARNINGS for files and folders:

build/python26/pkg/ : Keine Berechtigung
build/geoclue/pkg/ : Keine Berechtigung
build/openrct2/pkg/ : Keine Berechtigung
build/webkitgtk/pkg/ : Keine Berechtigung
build/pax/pkg/ : Keine Berechtigung
build/2048-cli-git/pkg/ : Keine Berechtigung
build/keeperrl-git/pkg/ : Keine Berechtigung
build/gnustep-gui/pkg/ : Keine Berechtigung
build/kodi-addon-pvr-iptvsimple-git/pkg/ : Keine Berechtigung
build/code/pkg/ : Keine Berechtigung
build/lix/pkg/ : Keine Berechtigung
build/geany-astyle/pkg/ : Keine Berechtigung
build/unvanquished/pkg/ : Keine Berechtigung
build/synfig/pkg/ : Keine Berechtigung
build/retroshare/pkg/ : Keine Berechtigung
.cache/pacaur/unagi/pkg/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/etc/openvpn/server/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/etc/openvpn/client/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/etc/audisp/plugins.d/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/etc/polkit-1/rules.d/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/etc/NetworkManager/system-connections/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/etc/sudoers.d/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/usr/share/polkit-1/rules.d/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/nfs/sm/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/nfs/sm.bak/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/gssproxy/rcache/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/portables/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/NetworkManager/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/rpcbind/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/machines/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/lib/private/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/cache/ldconfig/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/cache/private/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/db/sudo/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/var/log/private/ : Keine Berechtigung
projects/baschtstick/work/x86_64/airootfs/root/ : Keine Berechtigung
Games/lost+found/ : Keine Berechtigung
----------------
Scan WARNINGS: 37
[22.01.2019 11:06:53] Warzone 2100 backup completed with warnings.
[22.01.2019 11:06:53] Generating SHA-256 hash for Warzone 2100 backup file.
```

**Comment by MikeMaximus** [comment]
I'm not sure why it's doing this yet.  I tried a similar test case, I didn't get any permission errors but it seemed to take longer than it should have.

Does remove the trailing slash from the Save Path and just using "~" make any difference for you?

**Comment by basxto** [comment]
It’s possible that 7zip does not work how we expected it.

For the permission issues you first need files in your home directory, your user is not allowed to access.
In my case those folders were self-built arch packages and a live-stick based on arch, which contain files which must be owned by root later.
Usually you don’t have such files in your home directory.

You can create an empty test file with this:
```
touch ~/permissiontest # creates empty file
chmod go= ~/permissiontest # revokes permissions for group and other users
sudo chown root:root ~/permissiontest # changes user and group who own this file
```
Usually you would not notice when it traverses the whole home directory, it would only take longer.
In my case that is quite long since I have a nearly filled 1.5TiB partition at `~/Games`

**Comment by MikeMaximus** [comment]
Sorry I lost track of this issue until I noticed a reminder.  I'll have to look at this again before next release.  I'm not sure what i'll be able to do it about it since it appears it's just how 7z behaves when you use a wildcard in the base folder of an include.
