### ISSUE TITLE
Relative paths with Wine

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#162]
Relative paths like `.\save\` don’t get converted into Unix path `./save/`.
Besides that it’s looking good so far.

**Comment by MikeMaximus** [comment]
I usually use the folder browser or paste the path from windows explorer when I make configs, so the cases should always be exact on the official Windows list.

**Comment by basxto** [comment]
Theoretically the devs could change it and it would run without a difference on Windows.
I noticed this with Orcs Must Die! 2, the [game](https://steamdb.info/app/201790/config/) is `OrcsMustDie2.exe` and the [demo](https://steamdb.info/app/215020/config/) is `orcsmustdie2.exe`

**Comment by MikeMaximus** [comment]
That's true, I've had to update some configurations over the years because a patch changed the case on an executable.

Not sure what to do about that other than to just fix the configuration when the problem comes up.

**Comment by basxto** [comment]
Include and Exclude Items would also need `\` replaced with `/`.
> Not sure what to do about that other than to just fix the configuration when the problem comes up.

On Windows and Wine you could just convert process names and search strings to lower case and compare those. Maybe there is even a flag for ignore case. RegEx definitely supports that.

**Comment by MikeMaximus** [comment]
> Not sure what to do about that other than to just fix the configuration when the problem comes up.

I meant more in terms of when a Windows configuration Save Path has the wrong case and is imported into Linux.

Yes I could make the process detection case insensitive,  I actually was going to do that in one of the very first versions.  I had a reason for not doing it,  and now I can't remember what that reason is.

**Comment by basxto** [comment]
Maybe portability or less false positives.
