### ISSUE TITLE
Windows variables

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#163]
I need `%PROGRAMDATA%` for Peggle Extreme and Bejewled 2.
Wine does not really thave that one, it could be extracted from system.reg, but not easily.
Is it save to use `C:\ProgramData` instead? I guess rather not.

And whats the best way to handle the documents folder? I guess `%USERPROFILE%\*Documents`

Biggest pro of something like `%DOCUMENTS%` would be, that I don’t have to put something like `*Documents\BNE\One Piece Pirate Warriors 3\SAVEDATA\` into the item list.

**Comment by MikeMaximus** [comment]
%USERDOCUMENTS% for the Documents folder.

ProgramData is currently not handled at all.  I never ran across any games that saved in there.  Will have to add support for it.
