### ISSUE TITLE
Paths in include lists not working properly

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#164]
7za removes all folders from the path, which do not include place holders.
This can break the restore functionality.

`7za a -t7z -mx5 -i@/home/dabascht/.local/share/gbm/gbm_include.txt -x@/home/dabascht/.local/share/gbm/gbm_exclude.txt ~/game_backup_monitor/savegames/Amnesia:\ The\ Dark\ descent/Amnesia:\ The\ Dark\ descent.7z -r`

Does not work: (merges both into one folder)
```
"/home/dabascht/.frictionalgames/Amnesia/Main/*/*.sav"
"/home/dabascht/.frictionalgames/Amnesia/MainDemo/*/*.sav"
```
Does work:
```
"/home/dabascht/.frictionalgames/Amnesia/Main*/*/*.sav"
```
And this way always works:

`cd /home/dabascht/.frictionalgames/Amnesia/;7za a -t7z -mx5 -w/home/dabascht/.frictionalgames/Amnesia/ -i@/home/dabascht/.local/share/gbm/gbm_include.txt -x@/home/dabascht/.local/share/gbm/gbm_exclude.txt ~/game_backup_monitor/savegames/Amnesia:\ The\ Dark\ descent/Amnesia:\ The\ Dark\ descent.7z -r
`

```
"Main/*/*.sav"
"MainDemo/*/*.sav"
```

Setting the working directory with `-w` did not appear to work.

This is a new issue for #160

**Comment by MikeMaximus** [comment]
Looks good, so this changes the include/excludes to use relative references and we just set the working directory of 7za to the save folder.
