### ISSUE TITLE
Preselect last played game in Game Manager

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#166]
I’m going through many games and backup as well as restore them.
I think it would be helpful if Game Manager would select the last played game by default.
Maybe it’s easier to put the name of last played game in the Quick Filter.

This is an enhancement for power users.

**Comment by MikeMaximus** [comment]
I also had an idea once that clicking on the name of the last played game could automatically take you to it in the Game Manager.

**Comment by MikeMaximus** [comment]
GBM will now auto-select the last played game (if there is one) when the Game Manager is loaded.

Since the feature very low impact and I can't really see it annoying anyone, i'm not adding a setting to disable it.
