### ISSUE TITLE
Plugin brainstorming

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#167]
Could be sth like `plugin/config.ini` (either tag or process, not both at the same time)
```
name="Wine"
tag="wine"
process="wine-preloader"
regex=false
match=true
savepath=true
```

`plugin/match <process> <parameters> <working directory> <config process> <config parameters> <config savepath> <config regex>`
With return values 0 for match and 1 for mismatch.
Output like:
```
emulator=
sandbox=
custom1=
custom2=
gamepath=
```

`plugin/resolve <savepath> <gamepath> <config process> <config parameter> <emulator> <sandbox> <custom1> <custom2>`
Output like:
```
savepath=
```

`plugin/custombackup <tmp> <savepath> <include> <exclude>`
Which just returns 0 when the plugin wants to handle the backup and 1 when GBM should handle it. (wine files vs. registry)

`plugin/save <tmp> <savepath> <include> <exclude>` and `plugin/restore <tmp> <savepath> <include> <exclude>` also would be possible. 

GBM would just backup from and restore to a temporary directory and the scripts/programs do the rest.
Examples:
* Generate files from registry values (windows, wine)
* Extract save games for games that mix settings and save games (unity prefs)

A backup plugin for Windows run in Wine would need some form of prioritizing like `runbefore` and `runafter`.
Or dosbox run in wine/proton, it’s easier to set up.

Related to #113, #148, #151

**Comment by MikeMaximus** [comment]
I have ideas on how to work this into the next project i'm going to be starting, but I no longer have plans to implement plug-ins in this project.
