### ISSUE TITLE
Memory leak on mono

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#170]
Just noticed this morning that mono grew to over 10GiB RAM.
And the same thing just happened again. 
This morning I played a game, this time I just looked at my sessions (all of  them)

I haven’t used 1.15 much, but I think I would’ve noticed that before. Maybe related to a mono update, not sure. I installed 5.16.0.179 lat friday.

So it’s open whether it’s GBM’s or mono’s fault. (or both combined)

**Comment by MikeMaximus** [comment]
Sounds like they may have broke something in their implementation of .NET garbage collection.

I use Mono 4.6.2.7 and it usually hovers around 80mb max usage and stays there.  I'm not sure when, but I'll have to test that version of Mono on Antegros.  

I'm assuming it's no longer discarding any objects after a detection pass, which would start chewing up insane amounts of memory over time.  I could manually trigger garbage collection after each detection pass, with .NET it's not recommended to do that, but it could solve this issue in Mono.

**Comment by MikeMaximus** [comment]
I'm going to update one of my VMs to 5.16.0.179, hopefully i can see what's going on.

**Comment by MikeMaximus** [comment]
Using Mono 5.16.0.179 on Ubuntu 16.04 I haven't been able to replicate so far.  

Memory usage hovers between 80 and 90 MB while in detection mode.  

I used a database with over 400 configuration entries and ~1000 session entries.  I tried detecting a game and running a backup, as well as loading all the sessions in the Session Viewer.  None of which had any dramatic effect on the memory usage.

So I'm not sure what's going on here.  Maybe you'll be able pinpoint when the memory usage starts getting out of hand by watching the mono process in top as you use GBM.

**Comment by basxto** [comment]
Just now I saw it quickly (in < 1min) growing from 60MiB to 500MiB, but falling back as soon as I gave window focus.
Have not found a way to trigger it, had it in the background for hours and nothing happened.
Could be even that is only a thing between winform and my window manager, since I dictate the window size. Size changes of windows are mostly ignored, I’ve seen some windows who managed to enforce a minimum size, but they have not more control than that when they are not floating mode.
That means I have to try it with other window managers if I find a way to reproduce it.

**Comment by MikeMaximus** [comment]
The amount it grew seems so excessive for what GBM is doing, even if the garbage collector did clean it up once the window had focus.

I have had mono segfault a few times on Ubuntu 18.04, which could be related to the same issue of memory usage getting out of hand,  but I've never actually noticed the usage being that high.

**Comment by basxto** [comment]
I’ve a graph widget for RAM and my system freezes if a process uses up all RAM. I actually wonder why it does not get killed.
But when I start gbm RAM usage looks normal, growing and falling when it gets cleaned up.

**Comment by basxto** [comment]
It happens frequently, but I never saw it happen while playing a game.
I yet have  to try if just happens with the newest version.
That I haven’t seen it while gaming, could mean that it’s related to the game scanning part.

**Comment by MikeMaximus** [comment]
I was able to finally observe this happening on my test VM and I believe it's related to the System.Text.RegularExpressions.RegEx class.  Removing all regex configurations stops any erratic and excessive memory usage during each scan pass.

I'm going to make some changes around how RegEx is called to see if I can solve this problem.

**Comment by MikeMaximus** [comment]
I was able to greatly reduce the memory usage per pass by changing the way regex matches are tested, but there was still an issue with that memory never being released by the automatic garbage collection.  It was actually even more apparent with the new code, even though the memory usage increased much slower.

So I started manually triggering the GC after every pass and this seems to completely stabilize memory usage during scan mode.  I'm not sure how much this is affecting CPU usage, it doesn't seem to be an issue.

**Comment by MikeMaximus** [comment]
A v1.1.6 build is attached if you'd like to test these changes on your system.  

[GBM.zip](https://github.com/MikeMaximus/gbm/files/2562913/GBM.zip)

The database changes for v1.1.6 may not be final.  GBM will automatically backup the db files on upgrade as always,  but just a heads up.

**Comment by basxto** [comment]
I will see if I can try that one soon.

Running GBM with game manager open for over 12h worked without GBM eating my RAM.

**Comment by MikeMaximus** [comment]
Most modal windows, including the Game Manager will shut down the scanner while they're open.  Using "Stop Monitor" via the File menu or clicking Monitor Status on the bottom right to toggle it off should be enough to prevent it.

I'm pretty confident about the changes.  There's only a few little things I would need to look at and fix to finalize v1.1.6.  Once this issue is confirmed as fixed i'll make a release because i'm not sure when i'll be able to get at the larger features.

**Comment by basxto** [comment]
Will let it run the night and see what happens.
I decided to run a temporary full copy of gbm, this way I won’t screw any settings or backups in any way and can still use globally installed gbm for regular tracking.

```
mkdir -p /tmp/gbmtest/
cp -r ~/.local/share/gbm /tmp/gbmtest/
cp -r ~/game_backup_monitor/savegames/  /tmp/gbmtest/
cd /tmp/gbmtest/
wget https://github.com/MikeMaximus/gbm/files/2562913/GBM.zip https://raw.githubusercontent.com/MikeMaximus/gbm/master/gbm.sh
unzip GBM.zip
chmod +x gbm.sh
sqlite3 gbm/gbm.s3db "UPDATE settings SET BackupFolder= '/tmp/gbmtest/savegames/' WHERE _rowid_='1';"
XDG_DATA_HOME=/tmp/gbmtest/ ./gbm.sh
```

Is there anything else I should test for 1.1.6? I will go through the commit log a bit.

**Comment by MikeMaximus** [comment]
Sounds good, there are a couple other things you could look at.  [This is the list](https://github.com/MikeMaximus/gbm/milestone/21?closed=1) of what's been completed in that build.

**Comment by MikeMaximus** [comment]
How did it go @basxto?  

I've actually a different idea for a fix that doesn't involve using bad practices (GC.Collect).  

Since creating even one basic regular expression is such an expensive call in terms of memory and cpu usage, i'm just going to pre-generate them into memory and just keep them there.  This should fix Mono's issue with not cleaning them up and remove the minor cpu hit from scanning almost completely.

**Comment by MikeMaximus** [comment]
I've changed GBM to use precompiled regular expressions and to keep them in memory.  

This has reduced CPU usage by roughly 80% with ~150 regular expressions per scan pass.  It also seems to have fixed the memory leak in Mono, but that requires more testing to be certain.

Once I do some testing myself i'll post a new build in this issue.

**Comment by basxto** [comment]
I ran it for 2.5h days without any memory leak trouble.
Warning regarding unknown variable PROGRAMDATA wasn’t there, but did not test anything further

**Comment by MikeMaximus** [comment]
Great.  Thanks for testing!  

I tried some %PROGRAMDATA% Windows configurations in Linux and it didn't generate the warning for me.  I'll wait until you get a chance to play around with the build some more.

Yes it's now stored in a compiled state in the game object.  But it does not fix the memory leak, granted it's much much slower now.  So i'm going to have to continue using GC.Collect to solve this issue unless I can think of something else to try.

I think I may have to write up an issue for the Mono team.  I added new diagnotistic code that reports what Mono thinks the memory usage is as the scan code runs.  Mono is reporting memory usage patterns almost exactly the same as Windows and shows the garbage collector triggering correctly on it's own.  But it's not obviously not doing something that the manual trigger does, because the Mono memory usage keeps growing and growing, even though the diagnostic code in GBM shows the usage as normal.

**Comment by basxto** [comment]
I got that warning with 1.1.5, because it did not have that variable. And since 1.1.6 now supports that variable, I did not get the warning any longer.

**Comment by MikeMaximus** [comment]
Oh good.  Sorry, I misread "wasn't" as "was" in your previous comment so I thought it was still generating a warning in 1.1.6.

**Comment by MikeMaximus** [comment]
As per my [post edit above](https://github.com/MikeMaximus/gbm/issues/170#issuecomment-437968415),  it looks like I was premature with my findings and the regular expression preloading actually did fix the leak.

[GBM.zip](https://github.com/MikeMaximus/gbm/files/2577076/GBM.zip)

@basxto whenever you have time, if you want to give that build a run over night and see how it goes i'd appreciate it.

**Comment by basxto** [comment]
Runs well so far, but I played quite a bit fallout shelter, so it was not scanning all the time

**Comment by MikeMaximus** [comment]
Great, testing while using it helps me a lot.  I ran a 24 hour test just leaving it idle in scan mode and the memory usage patterns seemed normal.

**Comment by basxto** [comment]
#163 backup of Peggle Deluxe looks good
#166 works
Backup of Fallout Shelters looks good so far, but it is still my modified configuration.

**Comment by MikeMaximus** [comment]
I think this is resolved.  I'll likely release v116 this weekend or early next week at the latest.

**Comment by basxto** [comment]
I can’t await it.
You made some great improvements with the new version.
I hope I will finally get to adding some wine games to the windows list.

**Comment by basxto** [comment]
I will just run a separate gbm session in `/tmp`, import the windows configurations, add my own games, copy the game path to the comments, test my games, restore the game path, export and upload.
That should work, although not comfortably.
