### ISSUE TITLE
Illegal characters in save path error

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#172]
Illegal characters in a save path on the Game Manager (and probably the Add Game Wizard) can cause an unhandled exception when trying to use the Include/Exclude window.

This will probably crash right out in Mono,  but in Windows you can click continue and fix the problem.

**Comment by AdmiringWorm** [comment]
**Suggestion.**
Perhaps using [`Path.GetInvalidFileNameChars()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidfilenamechars?view=netframework-4.0) and [`Path.GetInvalidPathChars()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidpathchars?view=netframework-4.0) would be a valid solution to sanitise the path and the filename?

While it wouldn't catch everything, it will catch most invalid characters.
The methods are available in mono as well.

**Comment by MikeMaximus** [comment]
Thanks for the suggestion, it actually does use one of those functions for validation when attempting to save.  Its just currently not validating the path when it's sent to the include/exclude form prior to saving.
