### ISSUE TITLE
Wine detection does not update game path

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#175]
When you run a game with a different wine (wine vs. proton or a moved steam library) `Game Path` does not get updated.
I observed this with Fallout Shelter.
This is a problem since an update of a windows configuration does not clear that field.

**Comment by MikeMaximus** [comment]
Yes this is currently a problem, the changes in 1.1.8 will take care of this.  GBM will refresh the location each time the game is detected.
