### ISSUE TITLE
Official tag for wine games

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#176]
Currently it is impossible to distinguish imported games from own configurations.
I would also add `WinOfficial` or `WindowsOfficial` to games imported from Windows.

**Comment by MikeMaximus** [comment]
This should be resolved by other changes in 1.1.8, I won't be messing with the tags any longer when importing.

The OS will be an identifier on the configuration itself.  The core configuration will also no longer be modified when it's detected in Wine, Wine related details will be stored in new fields.

**Comment by basxto** [comment]
That sounds great, thank you.
This would also make it possible to migrate backups from winesteam to Steam Play.

**Comment by MikeMaximus** [comment]
The changes to resolve this are now in the v118 branch.
