### ISSUE TITLE
Game configurations with same name

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#177]
GBM shows a dialog when multiple configurations qualify for the detected process.
With Windows import it now happens that there are multiple configurations with the same name.
It would be good to show some differing tags if the name is the same:
* #Wine
* #Steam
* #Gog
* #Humble

It would also be helpful to show these in the Game Manager.

---
Another clash would be in the backup directory.
Maybe it is better to name the `.7z` files after the game id, but keeping the folder names.
This would also avoid to accidentially restore or overwrite backups from Windows configurations on Linux.

**Comment by MikeMaximus** [comment]
Yes that window should show the tags so you can pick the correct entry.

The tags are shown on the Game Manager, or did you mean showing the tags in the list box?

There is a setting to change the backup naming over to the Game ID for those situations.  I could put another option in there to mix using folder names with the ID, but I'll consider that after looking at the code again.

**Comment by basxto** [comment]
It was mainly meant for the popup.
It would be neat in the game list, but there are other ways to get that information and I do not expect that this would work with a normal list element.

**Comment by MikeMaximus** [comment]
It would be nice on the Game Manager, if it allowed resizing the form.   I should look into that.

Reminder for myself before releasing v1.1.8:

Make this cleaner by adding a new column for the tags.
