### ISSUE TITLE
Disk space warning when backing up to SMB share

### ISSUE THREAD

**Issue by dunestorm333** [MikeMaximus/gbm#180]
Hi,
I've got my backup directory set to a SMB share. Whenever I backup a game, I get a warning about not having enough disk space despite there being about 800GB free in the backup location. I noticed there's another thread about this issue which was closed but nothing specifically about storing you save-game data in a network location.

This issue goes away when I map the backup folder to a drive letter.

**Comment by MikeMaximus** [comment]
That's probably something I haven't re-tested in a long time. Sorry about that.

I'll take care of the disk space warning when using an SMB path for the next release,  for now it'll be have to be mapped to a drive letter as a workaround.  

Thanks for the report!

**Comment by MikeMaximus** [comment]
In the next version, the disk space check will be disabled if the backup folder is a UNC path.

.NET provides no managed way to get the available disk space of a location when only the UNC path is provided.  There are some hacks to make it work,  but they may cause other problems so I decided to just disable the check in this case instead.

**Comment by dunestorm333** [comment]
Cool! Another thing I wanted to mention is that on startup, it can take 20-30 seconds for UNC paths to automatically mount. I got around this by setting a scheduled task delay of 1 minute so that the share is ready before GBM tries to access it.

**Comment by MikeMaximus** [comment]
Right, that's also an annoying issue with using a share for the GBM backup path.  I took care of that for the next version as well.

On startup, it now waits and checks if the path exists every 5 seconds for a full minute.  If the path is still not available after a minute only then will the message appear, but it can now be canceled to continue waiting for the path become available.

This will also be handy if the backup path is on an external drive, now it can just be plugged-in during the wait or before pressing cancel on the message and GBM will automatically pick it up.

Thanks for reminding me about that as well. :+1:
