### ISSUE TITLE
Backup confirmation not taking focus

### ISSUE THREAD

**Issue by dunestorm333** [MikeMaximus/gbm#181]
I've noticed in quite a few cases that the backup prompt is hidden behind other windows after closing down a game. Sometimes one can forget that it's there, resulting in games not being backed up.

**Comment by MikeMaximus** [comment]
I can take a look into that again, I tried to fix it a long time ago but it was still inconsisent.  The confirmation can be disabled in Settings if you wish.

**Comment by dunestorm333** [comment]
Might give that a try! Though I like being notified once a backup has completed.

**Comment by MikeMaximus** [comment]
I worked out the focus issue, it'll be fixed next version.  There's a few other messages that should get focus as priority as well.
