### ISSUE TITLE
Environment variables in game path

### ISSUE THREAD

**Issue by arthurmv** [MikeMaximus/gbm#187]
I'm using variables for DRM-FREE games and Steam games paths. The issue is when I set these variables in Game Manager, GBM no detect them when those games are running, works only when I set absolute path instead.

I would like to use two computers with same game folders but in different location and drive. I tried to use Custom Path Variables and Windows environment variables, both together and separately, it didn't work.

**Comment by MikeMaximus** [comment]
Unfortunately Environment Variables and Custom Path Variables are not supported in the Game Path field.

I can see how it would be useful in that situation.  I'll add support for variables in that field in the next update.

**Comment by MikeMaximus** [comment]
This is ready for next version.  

Since GBM only supports specific Windows environment variables, you'll want to use a Custom Path Variable for your game folders to make this work.
