### ISSUE TITLE
Allow backups of currently not installed games

### ISSUE THREAD

**Issue by NewRavenGer** [MikeMaximus/gbm#189]
I actually intent to use GBM as a replacement for GameSaveManager while making use of the additional features it offers. And for the most parts, that works fine - with the option of custom variables I'm actually able to to things, GSM just can't in its current form (for example setting the personal SteamID as a variable which a few games like Life is Strange 2 or World of Final Fantasy use in their savegame path). However, one thing bothers me... the hard requirement of a process name to monitor if you create a new game profile. As GBM allows me to make manual backups if I already have a working profile even of currently not installed games, I just should be able to also create a profile without a process name given to do manual backups of currently not installed games.  I know I could workaround this by pointing to a never used executable on my system or just entering some gibberish, but that is just not a very clean way to do, especially as I intend to share my game profiles with my friends - as I already do with my GSM profiles, where already about 45 of them managed to get included in the official database over the time.

So, please allow us to use an empty Process field in the game manager. I don't mind to get a warning or anything like that, as watching the game process is an essential part of how GBM works and the option to manually initiate a backup is just a minor additional option - but in case someone like me actually want to use it, it would be really helpful to not being forced to enter something there.

Thank you :)

**Comment by MikeMaximus** [comment]
I can see where you're coming from, i'll look into allowing backup configurations without a process.

**Comment by MikeMaximus** [comment]
Is there a reason you closed this issue? I like to leave them open until they are evaluated, so I remember do it.

**Comment by NewRavenGer** [comment]
Nope, it was just me being a bit overzealous, sorry :)

**Comment by MikeMaximus** [comment]
I've decided to add support for this.

The ability to create a profile without a process will simply require "Monitor this Game" to be unchecked.

I may disable (but not clear) the Process field when the Monitor this Game is unchecked, just so the user has a visual indication that it's no longer required to save the configuration.
