### ISSUE TITLE
Issue with multiple variables in savegame location path

### ISSUE THREAD

**Issue by NewRavenGer** [MikeMaximus/gbm#190]
And... here I am again ;)

The issue:

I created a SteamID variable under Custom Path Variable. This variable actually doesn't contain any physical file system path, but instead it is set to my personal Steam-ID. This is required for quite a few games which include this SteamID in their savegame path. And a similar uPlay-ID is also required for most uPlay games. I guess that was not the initial purpose of that Custom Path Variable setting, but it is very useful this way.

Let's take a look at World of Final Fantasy, for example:
If I select the savegame path in the game manager, it - correctly - modifies it to `%USERDOCUMENTS%\My Games\WOFF\%SteamID%\savedata` after I click the save button. The physical path is `D:\Documents\My Games\WOFF\76561198011198852\savedata` (where 76561198011198852 is my Steam-ID and is set as a custom variable). This all works completely as expected. However, as soon as I try to actually do a backup with this, I get the following message: 

[20.07.2019 21:10:35] Backup aborted.  The saved game path for World of Final Fantasy does not exist.

I guess there is some issue with how this path is passed to 7z, but I can't really verify this, because even with verbose output, the message log doesn't give any more info, probably, because it checks the path before it got handed over to 7za.exe at all.

So, what I would expect GBM to do:

1. just pass the path over to 7-Zip as it is. As seen in the Game  Manager, the tool is already able to resolve more than one variable correctly and even if the initial purpose of the " Custom Path Variable" settings was to set an actual file system path, it's much more flexible that way. Besides that, not being able to use the custom variables "as string" instead of purely as "file system path" will result in being unable to share game profiles for a lot of games because their developers choose - for whatever reason - to include that individual information, which is different for every user, in their savegame paths. A few games who have that issue right now because of their dynamic savegame paths would be: Life Is Strange 2, Assassin's Creed 3, Assassin's Creed Origins, Batman: Arkham Knight and World of Final Fantasy. If you need to try a free game to test more about the issue, you could also try The Awesome Adventures of Captain Spirit on Steam.

2. I wouldn't like that second option, but... as the setting is named "custom path variables" and not "custom variables" you could also make sure, that only real file system paths are accepted here instead of string variables (like my steam id). In my opinion, that would harm the flexibility of GBM, however, it would at least solve the issue with having a correct path shown in the Game Manager under Save Path but being unable to actually make a backup.

**Comment by MikeMaximus** [comment]
Currently GBM can't handle when multiple variables (including environment variables) are in the same path.   An oversight on my part,  i'm surprised it hasn't come up before.  I'll have to rewrite the way it handles the path translation.

**Comment by NewRavenGer** [comment]
So the issue wasn't my "misuse" of the variables, but instead it was a more general problem which would have happened with any kind of multiple variables in paths...

Maybe it just didn't come up before because most users don't use variables because they don't need that flexibility. If I wouldn't like to share stuff like that, I probably would just use complete absolute paths, too and would therefor never run in this problem. But I like the idea to just have to change a handful variables and being able to use the monitoring and the backup function on every system with support for as many games as possible, so going the extra mile to use dynamic generated paths is well worth it for me.

**Comment by MikeMaximus** [comment]
Yes it was just a general problem I overlooked.  As soon as GBM encountered one custom path variable, it stopped evaluating the rest of the path for any other variables.  

I believe I already have it fixed and it will be ready for the next release.
