### ISSUE TITLE
Use a temporary folder for all backups operations

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#193]
To resolve an issue discovered while testing #156, GBM needs to perform all backup operations in a temporary location, before moving the resulting file to the backup folder. 

TODO:

1.  Allow the user to set a custom Temporary location in Settings, defaults to %LOCALAPPDATA%\gbm.
2.  Update disk space checks to check both the Backup Folder and Temp Folder.
3.  Update applicable backup logic to use the temporary location then move the file to the final location only when all operations on the file are completed.

It really should have always been doing this to make sure there was no file locking issues with any cloud sync software, but I never had any problems until trying to perform multiple operations on the same file.  Dropbox for instance can be extremely fast and grab the file before GBM can finish adding metadata to it.

**Comment by AdmiringWorm** [comment]
An alternative to a separate temporary directory for backup files, is to create a archive with the `.tmp` file extension, then rename it when you are done with the backup. I know these won't be backed up by dropbox, but ain't certain about other cloud services though.

This was the procedure we used in a different program for backing up save games that I helped out with a few years ago.

**Comment by MikeMaximus** [comment]
Hmm I didn't observe that behaviour with the temporary files and the current version of Dropbox, it really should have an option for excluding any file type though.

The exact problem I was having is that when 7z updates an archive, it makes a new version of it with a .tmp extension,  then deletes the original and renames the .tmp file.  Occasionally this operation would syncronize with Dropbox trying to index the original file when the delete/rename processed.  It would then fail because the file is locked and leave me a bunch of tmp files that did seem to get uploaded.

**Comment by AdmiringWorm** [comment]
I am sorry. I completely remembered wrong regarding using `.tmp` as a file extension to prevent upload.

It was the usage of `~` at the start of the file name and in combination with a `.tmp` file extension that actually prevented dropbox to upload the file to their servers, not the `.tmp` file extension alone.

**Comment by MikeMaximus** [comment]
Oh nice! That works.  Thanks, good to know that there is a way to do that.  I wonder why I couldn't find any information about that when I tried searching yesterday.  

I think i'm going to stick with the temporary folder just to make sure there's no issues with other cloud services, and since that implementation is already done and mostly tested.

**Comment by AdmiringWorm** [comment]
Fair enough. Just wanted to give you an alternative, maybe it could be useful in the future.
