### ISSUE TITLE
Is there a way to backup registry keys?

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#204]
I just started playing The Alto Collection on PC, and similar to A Short Hike, it's a Unity game that saves data to the registry:

https://www.pcgamingwiki.com/wiki/The_Alto_Collection
https://www.pcgamingwiki.com/wiki/A_Short_Hike

(EDIT: I just checked, A Short Hike only saves config to the registry; I'll swear it used to save games to the registry)

Is there a way to backup registry keys with GBM, since in this case, player progress is stored in ```Computer\HKEY_CURRENT_USER\Software\Team Alto\The Alto Collection```? I don't know how many games use this type of saving; can't imagine it's too common.

**Comment by MikeMaximus** [comment]
Yes you can setup a configuration to backup registry keys.

More details at http://mikemaximus.github.io/gbm-web/manual.html#registry

**Comment by Darthagnon** [comment]
Thank you so much!

**Comment by MikeMaximus** [comment]
You're welcome.  Let me know if you have any problems or questions.
