### ISSUE TITLE
[Suggestion] Option to Filter Official List by detected games

### ISSUE THREAD

**Issue by bellyrose** [MikeMaximus/gbm#205]
Since the official game list is so large, it'd be nice to have a checkbox next to the "select all" option to filter the list to only games that are detected on your PC.

**Comment by MikeMaximus** [comment]
That's a good idea, it's a bit of a nightmare to see what's actually selected when the list is that large.

Thanks for the suggestion.

**Comment by MikeMaximus** [comment]
The option will be available in the next update, along with other improvements to the import window outlined in the [readme.txt](https://raw.githubusercontent.com/MikeMaximus/gbm/master/GBM/readme.txt).
