### ISSUE TITLE
PDF/CHM of online instruction manual?

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#207]
Greetings, MikeMaximus!

Thank you for the new launcher features! It's looking really cool! To understand all the details, though, I needed to refer to the online instruction manual. Then I realised I needed an offline copy. Before I go and manually build myself a PDF or CHM (if I do, I will share it here), I just wanted to check:

Do you have some way on the backend of the site to generate a PDF or CHM of the GBM manual for offline reference?

**Comment by MikeMaximus** [comment]
You're welcome, I hope it's working well so far.  

I currently do not have a way to generate a nicely formatted pdf or chm from the online manual.  It is really something I should be providing though, in addition to the online manual.

**Comment by Darthagnon** [comment]
I'll build one. Should be done within the next couple of days, will post back here.

**Comment by MikeMaximus** [comment]
Thanks!

**Comment by Darthagnon** [comment]
Here you go, based off what you wrote on the website. CHM format (I tried rendering a PDF, but it didn't look good, and building and updating a PDF manually off the website content would be a major pain in Acrobat):

https://github.com/Darthagnon/gbm-manual/releases/

What do you think?

**Comment by MikeMaximus** [comment]
Looks good, I just find the line break on the section and sub-section on the top looks a bit strange.  

```
Help >
Manual
```

The style sheet could be changed so the content resizes to the window.  I've made a fork and I'll generate a pull request with that change.

One other minor issue is that Windows 10 blocks viewing unsigned chm files automatically.  I think the readme.md or the release notes should inform the user that they may need to go into the properties of the file and manually unblock the file after it's downloaded.

Thanks for your work on this!

**Comment by Darthagnon** [comment]
Ah, the navbar thingy? That was a default thing put there by WinCHM. I can remove from the template. I agree, it looks a bit weird. I'll do that once I figure out how to merge your pull request :D 

Will also add a note about Win10. Didn't know that; opened fine without warnings on my outdated Win10 v1709 PC - is it something from 1809 or something (think I heard that version added a bunch of signature requirements)?

**Comment by Darthagnon** [comment]
Uploaded the fixes. Had some trouble with Git; realised it hates me. Should be all good now.

**Comment by MikeMaximus** [comment]
Looks great, thanks!  I'll put a link to the repo at the start of the manual so users are aware it's available.

Yeah one of the more recent Windows 10 versions started automatically blocking apps and certain file types without signatures if they were downloaded from the internet.  It usually doesn't complain about opening them if they were created on that system. 
 The GBM installers and even GBM itself can be blocked by default, depending on the Windows protection settings.
