### ISSUE TITLE
[Feature Request] Launcher GUI

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#209]
General GUI suggestion/feature request:

Would it be possible to add more to the launcher GUI, possibly something like this?

![SmartSteamEmu Comfy Launcher](https://user-images.githubusercontent.com/20792748/101659461-fc956f80-3a3d-11eb-8edb-37384ad23267.PNG) 

([Source](https://cs.rin.ru/forum/viewtopic.php?f=10&t=91948), click on the "Old version" spoiler dropdown)

I use the context-menu launcher on the taskbar icon, but I don't find the Ctrl+L launcher search bar super useful at the moment because it's not a global shortctut, and not useful for browsing a list of games.

GBM already has the tech built-in to display extracted game EXE icons, names, paths and playtime data (as in the current GBM main GUI showing "last played game"). Was wondering if maybe the current main GUI could stay more-or-less the same, but have a scrollable sidebar with the gamelist added (as above), with the Ctrl+L search bar at the top of the GUI to filter the gamelist. By default it could show last-played or "no game detected" screen, but clicking on a name in the sidebar could populate the main view with the info that is currently displayed once you finish playing a game. Add a "Play" launch button  to the main view, to (re)launch the current game, and you've got a full launcher to rival Steam and Playnite.

**Comment by MikeMaximus** [comment]
I do like this idea.

The GUI features for the launcher are pretty rough as I was concentrating more on functionality for this initial release.  I was also wary about making large GUI changes to support it, as I wasn't sure how it was going to be received.  I always get annoyed when I'm using an app for one purpose, then the developers add new features and try to force them on me when I don't want them.  This is why I always make new GBM features not directly related to saved game backups disabled and hidden by default.

I'll think about it and see what I can come up with.  Thanks for the suggestion!
