### ISSUE TITLE
[Feature Request] Notification on completed backup?

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#211]
I was wondering if it would be possible to implement a (toggleable) Windows notification for when the current backup is complete, similar to the detection notifications? 

Use cases: backing up larger savedata with the GUI minimised to tray. I often find myself clicking "Yes, I want to backup data for X game" then waiting a while before I can sleep my computer, to make sure the backup is done; would be nice to know for sure for lazy users being impatient to check the log/GUI.

**Comment by MikeMaximus** [comment]
Sure, I can see how it would be useful.

**Comment by MikeMaximus** [comment]
I added this in 70bffd1.  It's a new option in the "Backup and Restore" section of settings.

When using this option only one notification is ever shown, informing you of which backup or how many backups were just completed.  So if you run multiple backups you won't be blasted with notifications. 😀

**Comment by Darthagnon** [comment]
Thank you so much! ❤❤❤❤
