### ISSUE TITLE
Tray icon not refreshing

### ISSUE THREAD

**Issue by Mondriaan123** [MikeMaximus/gbm#213]
Hello,
I would like to point to a little bug,
I admire your tool and use it on daily base.
There is a little bug that i notified, i dont think that its really your thing to solve but i would like to inform you.

I use a tool that is called Actual Window Manager and Nextstart that works like a hook.
When i run a game (i use Playnite because of the possibility to use Windows Powershell scripts), i stop the process AWM and NextStart (It looks like "Stop-Process -Name "Nextstart" and Stop-Process -Name "ActualWindowManagerCenter""), this two hooks influence the performance of the game in such a manner that i break them of. When i end the game i restart this processes from within Playnite (Start-Process "\ActualWindowManagerCenter.exe" and
Start-Process "\Winstep\Nextstart.exe"), the bug is that the GBM icon does not refresh from the little blue to the little green icon (the tool itself works flawless), the only way to get the green icon back is by restarting GBM.

Thank You
Mondriaan

**Comment by MikeMaximus** [comment]
Thanks for the kind words and the report Mondriaan.

Does Playnite restart those tools automatically the instant the game ends?  The only thing that comes to mind is that NextStart is re-initializing when you quit the game at roughly the same time GBM is switching between tray status icons and this is causing issues.  If this is the case you can try using the ```Start-Sleep``` power shell command to slightly delay restarting them to see if that makes any difference.

**Comment by Mondriaan123** [comment]
Oke i will use a short pause, i try 5 seconds.

Op vr 22 jan. 2021 om 02:49 schreef MikeMaximus <notifications@github.com>:

**Comment by Mondriaan123** [comment]
Looks like its working, even with a very short pause of 1 second.

Thank you

Op vr 22 jan. 2021 om 21:35 schreef Johan Daanje <maildt12@gmail.com>:

**Comment by MikeMaximus** [comment]
Glad to hear that solved the problem!
