### ISSUE TITLE
Export game path

### ISSUE THREAD

**Issue by arthurmv** [MikeMaximus/gbm#215]
I been had some issues on my two computers, it exports fine but without GAME PATH field, it would be useful because is needed for detect a game properly, I have some game.exe files in some games, but using the path it works fine.

Could we have game path info in export XML files? Please.

**Comment by MikeMaximus** [comment]
The XML export is meant for sharing configurations for any PC.  The game path is dynamic field and could be different on any PC, so it is not included.

If you're sharing a backup folder between two PC's that have games installed in the same location, you can enable "Game Path" syncing in "Settings -> General" using the "Choose Optional Sync Fields..." button.

**Comment by arthurmv** [comment]
So I don't need export any game? Would be just share the same folder with "Game Path" enabled and that's it?
I'm using custom path variables on both computers.

**Comment by MikeMaximus** [comment]
Yes if you share a backup folder, configurations will automatically sync between your PCs, including "Game Path" if you enable it.

**Comment by arthurmv** [comment]
Thanks!
