### ISSUE TITLE
Feature suggestion: Option to create a backup of the last played game at GBM startup.

### ISSUE THREAD

**Issue by NewRavenGer** [MikeMaximus/gbm#218]
Hi there, it's me again :) 
I don't know how feasible and most important how much of general use such an option would be. However, after thinking quite a bit about other solutions for my small problem - maybe with third-party-tools or scripts - I couldn't come up with anything really useful, reliable and working.

The problem: my girlfriend usually uses her PC in a remote way... gaming on her laptop via remote play, gaming on tv (and sometimes even on her android tablet) via Steam Link. The issue here is... she also shuts down the host (-> her PC) with these remote devices. In some - not that many - cases it happens, that Windows is already shutting down while GBM hasn't completed the backup, especially if there are  either larger savegames files (Minecraft, in our example) or many of them (Skyrim, in our example) so there is a lot of data to compress. I already tried to change the compression settings to "fast" and even store/none but that doesn't reliable help (and no, telling her "don't use that option, just walk the stairs up and turn of your PC like everyone else" didn't either). 

So, an option to simply just do a backup of the single last played game as soon as GBM starts (which would be when the PC is turned on again) would solve my issue here. So I would like to ask if something like that is possible to implement at some point.

(another option could be some kind of scheduler to create backups in fixed time intervals, but it seems a bit of bloat for GBM and maybe is not worth the required work, so therefor I think, the above option would be more suitable)

**Comment by MikeMaximus** [comment]
I'm pretty sure I can just delay the Windows shut down until a backup operation is completed, that will be the cleanest way to do it.

**Comment by NewRavenGer** [comment]
Thank you. Well, if this could solve the issue, that would be fine by me of course. 
However, I may add that something similar also came to my mind and I have already tried to start tools which should prevent a shutdown while running (some sync- and backup-tools) and none of them actually was able to prevent that behavior. Seems to me like Valve would use some fairly harsh methods to shut down the host system (acts something similar to shutdown -f). But even if I'm wrong here, as far as I know, the "WaitToKill"-TimeOut in Windows is, per default, 20 seconds which isn't enough for longer backup tasks. Not sure if it is even possible to delay the closing of an application any longer than that at all. On the other hand... usually you come up with even better solutions to my issues than I had, so I'm fairly sure this time it's no different.

**Comment by MikeMaximus** [comment]
The reason I think it can be done is because during the development of an older version, I once had a bug in the shutdown code that seemed to cause GBM to delay Windows shutdown indefinitely.  It would just sit on the waiting to shutdown screen until shutdown was forced.

But as you say Valve might be using a non-standard method of shutdown that may invalidate what I was doing to cause that behavior.

**Comment by NewRavenGer** [comment]
Well, if you want, I would gladly try a test build to see if it's working. I would actually prefer your "cleaner" way to do this myself, but if it's not working, we can still return to my "backup after restart"-idea, maybe.

**Comment by MikeMaximus** [comment]
Yeah definitely, that's what I was thinking,  I'll post a link to a build in this issue to try once I get around to working on it.

**Comment by MikeMaximus** [comment]
I've created a very simple test, this build will attempt to prevent Windows from shutting down in general while GBM is running.  If this works in your scenarios as well I'll proceed with the rest of the logic.

Backup your current GBM.exe and replace it with the one in the archive. 

[GBM - Prevent Shutdown Build (x64)](https://www.dropbox.com/s/nysi09d0ue7o0pf/gbm%20-%20prevent%20shutdown%20build%20%28x64%29.7z?dl=0)
Build: 2021-02-20T23:43:47
GBM.exe SHA256: 70D188C5F9C2E68F05A823B0732284C5FA48EABB296AB24607D267F783111E5B

**Comment by NewRavenGer** [comment]
Thank you. Nope, doesn't seem to do anything here... I tried a few options:

1. just having GBM in the background, doing nothing, trying to shut down the OS via start menu. PC shuts down.
2. having GBM in the background creating a (large) backup for a game and trying to shut down the OS via start menu. PC shuts down
3. with GBM in background, having a game running long enough to trigger a backup in Steams Big Picture, closed the game and try to shut down the PC with the Steam Big Picture menu. PC shuts down.
(4. with GBM in background, having a game running in Steams Big Picture and try to shut down the PC without even closing the game. PC shuts down.)

Well, 4 hasn't anything to do with GBM, but I was not amused to see that Steam even actually offers to shut down windows without quitting the game.

However, none of the shutdowns were prevented and they didn't even seem to take any longer. I will try one the second PC now, but that probably will take a few minutes. I will edit the results in here :)

**Comment by MikeMaximus** [comment]
Hmm I just tested it again to make I packaged the right executable.  It prevented shut down or sign out then timed out back to Windows after a period of time. 

What version of Windows are you using?

**Comment by NewRavenGer** [comment]
Nope, nothing of that ever happened here. It didn't even show that "waiting for applications to close" screen which you sometimes get when programs are still running while you try to shut down or restart in the first 3 cases (it did show that screen a short moment on test 4, but hadn't even listed GBM there, only Steam itself and the not closed game). Is it that screen where it "stuck" for you before it went back after the time-out? Because if it was, I may have an idea why it didn't work for me...

This would be the German version of Windows 10 20H2 (19042) on both machines.

**Comment by MikeMaximus** [comment]
I discovered why it's not working, it only prevents shutdown if the main window is shown and not hidden in the tray.  It doesn't need focus, it just needs to not be hidden.  I'm assuming this is some kind of prevention mechanism for people that are coding malware to take advantage of this, but I need to dig a bit more.

**Comment by NewRavenGer** [comment]
Yeah, figured out the same thing probably at the same time as you did :) Plus... you should absolutely not have Windows to AutoEndTasks via registry setting. So, with the main window open and reverting that Windows setting, I could reproduce what this new version should do. 

The "waiting" screen was there for about 20 seconds, that I got logged out. After I logged in again, GBM was still active, the window was still open, however, the backup process failed, but I guess that was to be expected (probably because there wasn't a user logged in and the backup couldn't be finished in these 20 seconds)

**Comment by MikeMaximus** [comment]
Hmm I wonder if it's because the backup process is actually a spawned 7za.exe and that IS being closed.   I wasn't counting on that. 😞 

I think we will need to go with your idea.  I was thinking that if GBM detects a shutdown call while a backup is running,  it can just auto-queue it for next start up.

**Comment by NewRavenGer** [comment]
Seems that way. However, if GBM has started that 7za child process (which is has and windows also registered it that way, according to process explorer), shouldn't it stay active as long as GBM.exe is active (unless GBM closed it or it finished it's job, of course)?

But maybe that restart-thingy isn't even that bad. You could probably already set-up that "backup on the next start-up"-task right before the actual backup starts and right after the backup is triggered. If it finishes without issue, you just could remove that "task" at the end again. This would probably be quite transparent, it would not add any backups which aren't needed, and you wouldn't even add any options for it. On the other hand, I can clearly see why you aren't that happy with such a solution, but I ran out of ideas how to solve this otherwise myself, too, so I probably won't be much of a help.

**Comment by MikeMaximus** [comment]
Yes you'd think that's how it would work since 7za is a child process of GBM, but I can't see any other reason GBM would indicate that the backup failed once the 20 seconds was up.  Do you recall the exact wording in the log?  Did 7za show an error or did the output just end?  If GBM states "operation failed due to an error" means that 7za shut down unexpectedly.

Thanks for the ideas, I'll think on it a bit more.  It is something i'd like to solve for you.

**Comment by NewRavenGer** [comment]
Well, I redid the whole thing and that's the log:

`[21.02.2021 14:21:38] A sync from the master game list has been triggered.
[21.02.2021 14:21:39] 0 change(s) synced.
[21.02.2021 14:21:39] Game List (182) Loaded.
[21.02.2021 14:21:56] A sync to the master game list has been triggered.
[21.02.2021 14:21:56] 0 change(s) synced.
[21.02.2021 14:21:56] Game List (182) Loaded.
[21.02.2021 14:21:56] Adding The Elder Scrolls IV: Oblivion to backup queue.
[21.02.2021 14:21:57] The Elder Scrolls IV: Oblivion Save Folder Size: 7,75 GB
[21.02.2021 14:21:57] Backup of D:\Documents\My Games\Oblivion\Saves in progress...`

However, above the log window it says:
"Last Action: The Elder Scrolls IV: Oblivion backup failed at 2:22 (sic!) ."

**Comment by MikeMaximus** [comment]
Thanks for checking again,  I tried my own test as well, it's kind of frustrating that I can't use the debugger while testing this scenario. 😀 

I'm fairly certain now that in addition to killing child processes it's also killing all other threads except the main UI thread, which is why the backup output simply ends and the main thread reports a failure.  I think these are security measures in .NET so you can't pull any malware type shenanigans during shutdown.

I'm going to work on another solution,  I can't give you a time estimate, but I'll update this issue when/if there's anything you can test.
