### ISSUE TITLE
Can "Game Path" take account if full path is entered?

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#226]
I finally got around to ditching the old v125beta homebrew build I was using (and was causing database problems, hence why I hadn't updated yet). I'll do a writeup in "Discussions" about the steps I went through to fix it, in case anyone else has the same problems.

I noticed when adding paths to the "Game Path" field, I felt the instinct to enter the full path, including the EXE:
```E:\Program Files\Games_portable\AShortHike\AShortHike.exe```

However, launching the game results in GBM (v1.27) trying to call ```E:\Program Files\Games_portable\AShortHike\AShortHike.exe\AShortHike.exe```.

Easy solution, I trimmed the EXE from the full path. But had a thought - would it be possible to implement some sort of auto-check and trim, e.g. if the "Game Path" field ends in ```.exe```, remove up until the last backslash, and save that?

Of course, none of this is an issue when using the ```[...]``` button to pick the Current Folder, but then my workflow to find a game's EXE usually means "use voidtools' Everything to search for GameName.exe, open containing folder, copy path, paste"

Feel free to ignore this issue, it was just a thought I had...

**Comment by MikeMaximus** [comment]
It shouldn't be a problem to trim the executable off when saving.

**Comment by MikeMaximus** [comment]
Just a note that this trim feature is being reverted in 1.2.9.  It has been causing too many issues and doesn't work properly in all situations.
