### ISSUE TITLE
Incremental or differential backups

### ISSUE THREAD

**Issue by tepiloxtl** [MikeMaximus/gbm#228]
Some games create big save data, or many save data files (ie. Minecraft, which save data directory can go up into tens of gigabytes), and doing full backup of its directory is both very time consuming and wasteful of available space, if you want to keep more than one backup for rollback. Can either differential or incremental backups be implemented?

**Comment by MikeMaximus** [comment]
Thanks for the suggestion tepiloxtl.

I can implement differential backups, but I can't offer an estimate of when I can get to it.

**Comment by MikeMaximus** [comment]
v1.2.8 will have support for differential backups.  

It's currently implemented in the development branch, but it needs a lot of testing before I'll be comfortable with releasing it.
