### ISSUE TITLE
An attempt was made to access an exiting process

### ISSUE THREAD

**Issue by Mondriaan123** [MikeMaximus/gbm#230]
Hi, I've been using your app for a while now and am happy about it, now there is a strange bug that you might be aware of. If a game does not close properly (probably badly programmed), the game remains as a kind of ghost and is impossible to get out except by restarting the entire computer. This in itself is not so bad just your app keeps thinking that the game is still running and the only way to fix it is to restart the whole computer. Only restart GBM does not work because if the app is restarted GBM will immediately react to the game again. Is this known to you? Thank you. Mondrian.

**Comment by MikeMaximus** [comment]
Hi Mondriaan, in situations were a game doesn't exit cleanly, you should be able to use the Task Manager to end the game process instead of rebooting.  Once you end the game process then GBM will see it as closed.

**Comment by Mondriaan123** [comment]
No it is not working, access denied, there are hundred of people that notify about the problem, the process is closed but windows thinks that it is still existing and thats why GBM also thinks that it is working, when trying to terminate it it says that acess denied even when i enable full access, i only can restart windows, otherwise GBM keeps having a problem.

**Comment by MikeMaximus** [comment]
Have you tried stopping the process using ```taskkill``` from an administrator command prompt or ```Stop-Process``` in PowerShell?

As an option instead of rebooting, you could stop monitoring in GBM,  open Game Manager and uncheck "Monitor this game" for the offending game, then start monitoring again.  This would be a pain as you'd have to keep turning that option on and off every time you play that game, but might be better than rebooting if you can't kill the process.

I've never ran into this issue outside of Windows protected system processes.  Which game is doing this may I ask?

**Comment by Mondriaan123** [comment]
I have all permission to close the file but have now found what actually locks things, I use an app called Playnite to manage my games, nice program but this app blocks a lot of games and the only method to solve the problem, Playnite is first to close, then GBM also understands that the game is closed, then I can turn the Playnite app back on

**Comment by Mondriaan123** [comment]
I have also tried to make it clear to them at Playnite that something is wrong, maybe you can reproduce the problem, it takes place in Cossacks 3, among other games

**Comment by MikeMaximus** [comment]
Does the game close correctly when it's launched directly and not from Playnite?

**Comment by Mondriaan123** [comment]
Yes, the problem IS Playnite

**Comment by MikeMaximus** [comment]
I see, well it sounds like Playnite is launching the game as a child process, then something odd is occurring that prevents it from ending until the parent process ends.  This is something a contributor on that project would want to look into.

Other than the workaround I offered there isn't much else I can do to help with this, GBM is just doing what it's designed to do when a process it's told to detect is running.

**Comment by Mondriaan123** [comment]
Oke Thanks MikeMaximus

**Comment by Darthagnon** [comment]
Hey, @Mondriaan123 have you looked into the compatibility fixes for Cossacks? e.g. [this one](https://verokster.blogspot.com/2018/05/cossacks-american-conquest-gl-wrapper.html), to make it run properly on modern systems (there were another one or two, but I need to find them again; both were on GitHub)

**Comment by Mondriaan123** [comment]
Hello, thanks for your tip the game works perfect, it is only the exitting of the game that is a problem.
