### ISSUE TITLE
If Backup Folder is renamed, GBM won't open any longer

### ISSUE THREAD

**Issue by redactedscribe** [MikeMaximus/gbm#244]
If the Backup Folder is renamed (i.e. is moved), GBM will run, but no window will appear. Clicking the tray icon has no effect either. Only restoring the previous name, killing and re-running the program will remedy the issue.

Whilst writing this issue, after ~30-60s, a pop-up appears with options to fix the situation. Great, but there's no indication anything is happening; maybe the tray icon could at least read something like "Searching for backup folder..."? It just reads "Not scanning" (I've turned off enabling scanning on startup) as it waits (more like "as it hangs" from the user's perspective).

Thanks.

GBM v1.2.8

**Comment by MikeMaximus** [comment]
It waits for up to a minute for the backup path to become available for situations when the backup path is on a network drive that isn't mounted instantly on log-in.  

I can take a look again.  I remember having issues trying to implement a GUI indication at that point in the start-up code,  probably crashed in Linux as Mono and .NET behave a bit differently with the way events fire on startup.

**Comment by MikeMaximus** [comment]
The tray icon will now be more informative when this occurs.  The icon itself now better reflects there is a problem and the tool-tip includes a countdown that updates every few seconds.

This is the best I can do without making sweeping changes to how the app starts.

![image](https://user-images.githubusercontent.com/15719732/130827852-fac40381-bbc4-47b3-ab26-40c96e142b1d.png)
