### ISSUE TITLE
Chinese translation for GBM

### ISSUE THREAD

**Issue by Juijote** [MikeMaximus/gbm#245]
I have Chinese translation for GBM, will it incorporate multilingual support?
Resources.resx has been sent to the specified email address

**Comment by MikeMaximus** [comment]
This translation will be included in v1.2.9 and applied on any system using a Chinese language setting on their OS.

But I do have a question @Juijote.

Can your translation be used for any Chinese culture code?  Or only one of the specific ones listed below?

zh-CN | Chinese - China
zh-HK | Chinese - Hong Kong
zh-MO | Chinese - Macau
zh-SG | Chinese - Singapore
zh-TW | Chinese - Taiwan
zh-CHS | Chinese (Simplified)
zh-CHT | Chinese (Traditional)

**Comment by Juijote** [comment]
Because there is now only one Chinese translation, mine is Simplified Chinese, which is proposed to be available for all regions.

The reason is this, Simplified Chinese is the official standard script in China and Singapore, while in Hong Kong, Macau and Taiwan Traditional Chinese, which has not been simplified before, is used.

There will be differences in language and vocabulary habits, but there is no problem in understanding them. the reason why there are two sets of scripts is because it is difficult to learn to write and identify Traditional Chinese, and in order to effectively popularize education and eliminate illiteracy, Simplified Chinese emerged.

Back then, due to political reasons, some regions never accepted Simplified Chinese, but nowadays, young people can generally still recognize both sets of characters.

**Comment by MikeMaximus** [comment]
Thank you for the detailed explanation!
