### ISSUE TITLE
[Feature request] Extract game icon from EXE?

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#246]
I can easily extract game EXE icons to ICO using [Resource Hacker](http://angusj.com/resourcehacker/), but I was wondering if it would be possible to do so without the extra steps directly in GBM when selecting an icon? Currently, only ICO files seem to be supported, maybe PNGs? but definitely not EXEs

**Comment by MikeMaximus** [comment]
On Windows, any ICO, BMP, GIF, JPEG, PNG, TIFF should work in the Icon field if they are a reasonable size.  On Linux it's a little different, for example ICO files do not work but I don't know the supported types off-hand.

I can see about it automatically pulling the icon from an exe provided in the icon field.

**Comment by Darthagnon** [comment]
I wasn't sure about supported icons, as the filters on the selection window were ```ICO``` and ```All Files```, and EXE didn't work with all files

**Comment by MikeMaximus** [comment]
Yeah the filters should have been updated to include what actually works, it's just a feature I've not touched for a few years.

**Comment by MikeMaximus** [comment]
You will now be able to select an exe file in the Game Manager "Icon" field to have GBM use the default icon embedded in that executable.

I've also updated the open file dialog filters for both Windows and Linux to reflect which files types are supported.

Windows: ICO, BMP, GIF, JPG, PNG, TIF, EXE
Linux:  GIF, JPG, PNG, TIF
