### ISSUE TITLE
Small issue with the game path browse button in Game Manager when using path variables

### ISSUE THREAD

**Issue by NewRavenGer** [MikeMaximus/gbm#258]
As you probably know by now, I'm a huge fan of using path variables and only because of my complaining, you can chain them now ;) Sooo, while this works for the save path fine in the sense of it actually being working and also in the sense of "the browse button" in Game Manager correctly converts the variables back to the actual path and opens the browse window, the same doesn't seem true for the browse button for the actual game path field. It didn't come to my attention earlier, because I have only very few titles where the executable is named the same and therefore the game path entry doesn't matter most of the time, but in very rare cases, I need it anyway. So while I'm fairly sure, the detection also works with variables, it would be nice if the browse button in the game manager would work, too and would resolve the variables before opening the browse window, just like it's the case with the browse window for the save game path.

Small example:
have a path variable named gamedrive and one named goglibrary

gamedrive would be "C:" and goglibrary would be "gog". So, the path would be something like

%gamedrive%\\%goglibrary%\\Randomgame for a game installed in C:\gog\Randomgame

if I put %gamedrive%\\%goglibrary%\\Randomgame in the "Save Path" field in game manager, it opens - correctly - C:\gog\Randomgame after I push the browse button. but if I put %gamedrive%\\%goglibrary%\\Randomgame into the "Game Path" field and press the "browse" button, I end up in my documents folder, because seemingly the path doesn't get converted back.

Thank you :)

**Comment by MikeMaximus** [comment]
Thanks for the report!  I'll take care of it for the next version, which will arrive some day. 😄

**Comment by MikeMaximus** [comment]
Also fixed the Process and Icon browse to properly open to the Game Path when using path variables.
