### ISSUE TITLE
Missing Translation Strings

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#263]
This issue will be used to track strings that are missing translation to other supported languages by version.  

I welcome any help and will update the missing strings in subsequent releases.

### All currently missing strings have been translated and will be included in v1.3.3.  

See https://github.com/MikeMaximus/gbm/issues/263#issuecomment-1254130623 if you'd like to manually update your current release.

**Comment by Juijote** [comment]
> This is the missing Simplified Chinese translation for versions 1.3.0-1.3.2.
> 
> ### v1.3.2 - Simplified Chinese
> App_ConfirmDirtyWizard	向导还没有完成，你确定要关闭[BR][BR]？这将失去所有进度。
> App_AppendCopy	(复制)
> frmGameManager_cmsEnabled	&允许监控
> frmGameManager_cmsMonitorOnly	　&游戏运行结束时不备份
> frmGameManager_ErrorNoFileExists	文件不存在
> frmGameManager_ErrorNoFolderExists	该文件夹不存在
> frmGameManager_ConfirmMultiSave	你确定要对选定的游戏[PARAM]保存以下更改吗？ 允许监控[BR][BR]：[PARAM][BR]运行结束时不备份：[PARAM]。
> frmGameManager_btnCopy	&复制
> frmGameManager_ttHelp_btnOpenGameFolder	打开游戏文件夹
> frmGameManager_ttHelp_btnOpenSaveFolder	打开游戏存档文件夹
> frmGameManager_ConfirmCopyMulti	你确定要复制选择的游戏[PARAM]？
> frmAdvancedImport_chkHideIgnored	隐藏忽略项
> frmAdvancedImport_cmiIgnore	忽略
> frmAdvancedImport_cmiIgnore_Reverse	取消忽略
> frmAdvancedImport_cmiIgnore_Toggle	切换忽略项
> frmAdvancedImport_IgnoredCount	[[PARAM] 忽略]
> frmMain_gMonOpenBackupFolder	&打开备份文件夹
> frmFilter_FieldEnabled	允许监控
> frmFilter_FieldMonitorOnly	游戏运行结束时不备份
> ### v1.3.1 - Simplified Chinese
> frmAdvancedImport_WarningNoSavesDetected	没有检测到新的游戏存档
> frmAdvancedImport_DetectingSavedGames	检测已有的游戏存档... 请等待
> frmAdvancedImport_Processing	处理中... 请等待
> frmAdvancedImport_Importing	配置中... 请稍等
> mgrMonitorList_CustomListURLInfo	输入支持文件的完整URL，支持GBM XML和Ludusavi YAML文件。
> mgrMonitorList_CustomListURLTitle	从URL导入文件
> mgrMonitorList_ChooseImport	选择一个有效的文件来导入
> mgrMonitorList_XML	GBM导出
> mgrCommon_ErrorAccessingWebLocation	访问时发生错误：[BR][BR][PARAM][BR][BR][PARAM]
> mgrCommon_ErrorReadingTextFile	读取文本文件时发生错误：[BR][BR][PARAM]
> mgrCommon_ErrorUnexpectedWebResponse	发生错误（[PARAM]）：[BR][BR][PARAM] 。
> frmGameManager_cmsLudusavi	&Ludusavi Manifest...
> frmMain_gMonFileImportLudusavi	&Ludusavi Manifest...
> frmSettings_chkStorePathAutoConfig	启用自动配置商店路径
> mgrMonitorList_WarningLudusaviImport	Ludusavi Manifest列表包含数以千计的来自PCGamingWiki的保存游戏配置文件。[BR][BR]这些配置未经测试，可能与GBM不完全兼容。
> mgrLudusavi_ErrorConverting	在Ludusavi数据转换过程中，发生错误：[BR][BR][PARAM]
> mgrLudusavi_ErrorReading	在处理Ludusavi数据时发生错误：[BR][BR][PARAM]
> mgrMonitorList_ErrorImportFileType	文件或URL不包含支持的文件扩展名。
> frmLudusaviConfig_ErrorOperatingSystem	至少要选择一个操作系统。
> frmLudusaviConfig_ErrorProfileType	必须选择至少一个配置文件类型。
> frmLudusaviConfig_FormName	Ludusavi选项
> frmLudusaviConfig_grpSearch	快速搜索
> frmLudusaviConfig_grpProfileTypes	配置文件类型
> ### v1.3.0 - Simplified Chinese
> mgrMonitorList_CustomListURLError	该值必须是一个有效的HTTP或HTTPS地址。

**Comment by MikeMaximus** [comment]
Thank you Juijote!  The missing Simplified Chinese strings will be available in the next release.

You can also download the following file and extract it to the "zh" folder where you currently have GBM installed to update the current release.

[GBM.resources.zip](https://github.com/MikeMaximus/gbm/files/9619711/GBM.resources.zip)
