### ISSUE TITLE
Saving in Game Manager doesn't save until Game Manager window is closed

### ISSUE THREAD

**Issue by redactedscribe** [MikeMaximus/gbm#274]
Ideally, pressing _Save_ would immediately write to the "gbm.s3db" file instead of waiting to write until the Game Manager window closes. Currently, it's possible to _Save_, kill the GBM process, re-run GBM and find that your changes were not saved.

Maybe there's a good reason why it's built like this? If so, perhaps _Save_ should be renamed something like "Save on close"? Or, simply "Update" and perhaps add some text to the title bar or footer to say "Saves on close"?

As it stands, after pressing _Save_, there is no indication that the changes have not yet been written to the disk. For example, an asterisk somewhere, or italicised text on edited games in the list would help indicate uncommitted data.

Thanks.

GBM 1.3.1
Windows 11

**Comment by MikeMaximus** [comment]
I had already planned to fix this in 1.3.2, data will no longer be lost if the process ends before the Game Manager is closed.
