### ISSUE TITLE
Feature to duplicate a game manifest

### ISSUE THREAD

**Issue by redactedscribe** [MikeMaximus/gbm#275]
Sometimes imported game manifests don't contain a bit of data that you'd find useful to be backed up, for example a game's user configuration files, but to include them means to edit the manifest. However, if you choose to import a manifest from the Official list or Ludusavi (etc?), GBM will now claim that there's an update available for that edited manifest.

Unless you remain aware that you've edited a particular manifest, you may choose to update it thinking that there's necessary changes which improve the its ability to store important game saves / config files. Doing so would cause you to lose your custom changes.

I've found it a common practice to create a new manifest and base it upon the field values of an imported one, just to modify it slightly, and to avoid accidental loss since it won't show up as needing an update. I think it would be convenient to be able to duplicate a manifest to be able to use it as a starting point to store your customised version. Maybe a "Copy" or "New from" button in the Game Manager would be how this could be done?

Another solution could be to freeze or lock a manifest so that it can no longer be updated, but that's of course at the cost of never receiving further updates. (I assume manifests do get updated from time-to-time for example if it's known that a game has started producing an extra file that would also make sense to be backed up).

Thanks.

GBM 1.3.1
Windows 11

**Comment by MikeMaximus** [comment]
I run into this myself occasionally.  Adding a flag to "Lock" a configuration may be the most apparent and user-friendly way to handle it.

**Comment by redactedscribe** [comment]
I agree, however there may still be a time and place for copying manifests. A lock feature would be higher priority if both features were considered as I assume more people would immediately benefit from it. If #280 is deemed something worth pursuing, the circumstances when copying a manifest would be desirable would diminish further.

**Comment by MikeMaximus** [comment]
I'm going to look into the Copy feature as well,  it shouldn't be too difficult to add.

**Comment by MikeMaximus** [comment]
The Copy feature has been added with multi-select support.  

The Lock feature was added, but I've removed it because I feel the new Ignore feature on the Import window makes it redundant.

**Comment by redactedscribe** [comment]
> The Lock feature was added, but I've removed it because I feel the new Ignore feature on the Import window makes it redundant.

So now we should be able to ignore a manifest from being detected, and prevent, or "lock", a manifest from updating by simply copying it (since it gains its own unique UUID). The idea was effectively redundant indeed. Thanks for the copy feature however, it'll come in handy.
