### ISSUE TITLE
Death Stranding official manifest has wrong Save Path

### ISSUE THREAD

**Issue by redactedscribe** [MikeMaximus/gbm#277]
The official Death Stranding manifest imports with "%LOCALAPPDATA%Low\KojimaProductions\DeathStranding" defined as the Save Path when it should actually be "%LOCALAPPDATA%\KojimaProductions\DeathStranding" (it's in Local not LocalLow). My game is the Epic Games Store version if that matters.

Not sure if this is the right place to report such things, but hopefully it can be addressed.

Thanks.

GBM 1.3.1
Windows 11

**Comment by MikeMaximus** [comment]
Thanks it'll be fixed shortly with the next list update.

I prefer official configuration problems to be posted in https://github.com/MikeMaximus/gbm-web/issues.
