### ISSUE TITLE
Error when searching Ludusavi for games to import (List no longer searchable)

### ISSUE THREAD

**Issue by redactedscribe** [MikeMaximus/gbm#282]
Not sure why this is happening now because it previously functioned as expected, but when I search the Ludusavi list, I get:

```
---------------------------
Game Backup Monitor
---------------------------
An error has occurred during Ludusavi data conversion.



Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------
```

```
---------------------------
Game Backup Monitor
---------------------------
This list does not contain any new games to import.
---------------------------
OK   
---------------------------
```

I lost Internet connection during the first time I encountered the issue and there was actually a third popup box which appeared (before the other two):

```
---------------------------
Game Backup Monitor
---------------------------
An error has occurred reading the text file.



Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
---------------------------
OK   
---------------------------
```

It is no longer possible to search and therefore import any manifests from Ludusavi.

Maybe I need to delete some file so that a fresh copy is fetched?

GBM 1.3.1
Windows 11

**Comment by redactedscribe** [comment]
Found the answer: Deleting both "manifest.etag" and "manifest.yaml" files from %LOCALAPPDATA%\gbm on Windows and performing a new search caused them to be re-downloaded and now the Import Game Configurations window works as before.

I noticed that "manifest.yaml" was 0 bytes on disk prior to deletion, so it was probably that file alone that cause the issue.

**Comment by MikeMaximus** [comment]
Thanks for the report.   I'll update the error handling to delete the files automatically or change the order the etag is created so it doesn't get stuck that way after a download failure.
