### ISSUE TITLE
Any thoughts on adding the ability to periodically upload game save to webdav?

### ISSUE THREAD

**Issue by Juijote** [MikeMaximus/gbm#286]

**Comment by MikeMaximus** [comment]
I don't plan to add support for any specific file transfer protocols or cloud services to GBM.  It was always my intent have other software handle the file synchronization and use whatever service or protocol they want.

You could try mounting a webdav location as a drive, then use it as the GBM backup location.  If you're on Windows I would also recommend [GoodSync](https://www.goodsync.com), it supports a large variety of cloud services and file transfer protocols, including webdav.
