### ISSUE TITLE
v1.3.3 - Excessive padding?

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#290]
Is it just me or does v1.3.3 have more padding than before?

![GBM_rYWkM9aPOH](https://user-images.githubusercontent.com/20792748/203440063-c8d3d6cf-6531-4ee3-8c1b-b30d387eccc6.png)

125% HiDPI 1920x1080 Win10v1709 with [XP Explorer HiDPI fix](https://windows10-dpi-fix.xpexplorer.com/)

**Comment by Darthagnon** [comment]
I do need to update my graphics drivers, and it was fairly recently I went back to 125% scaling instead of 100%, so it could just be me, but the padding around the items seems a lot larger than I remember.

**Comment by MikeMaximus** [comment]
I haven't had this problem myself or any other reports.  It looks like it's not properly anchoring the controls to the window size on your system.  It is very likely related to the DPI setting and custom fix.  You can try changing the DPI settings in the properties of GBM.exe (Compatibility Tab) to see if that makes a difference.

**Comment by Darthagnon** [comment]
Tested DPI compatibility settings, which haven't made a difference.

I'll now tinker with the DPI fix (it's apparently based off Win8.1 scaling), see if that makes a difference.

**Comment by MikeMaximus** [comment]
I replicated what you're seeing by setting the High DPI scaling override to "Application", which makes sense because GBM doesn't do any DPI scaling on it's own.  

I got the best results using the System (Enhanced) setting, but I'm not sure if that is available on your old version of Windows 10.

![image](https://user-images.githubusercontent.com/15719732/203562384-30fa7542-e9da-47de-84d1-5100cf76f241.png)

**Comment by Darthagnon** [comment]
Aha! I tried System (Enhanced), but (probably because of the Win8.1 DPI fix) that didn't do anything.

**Comment by Darthagnon** [comment]
I disabled the custom scaling mod (using Win10 v1709 built-in scaling).

### Results:
- Normal: correct scaling, but very blurry (as often happens with HiDPI screens), including the tray context menu
- Scaling performed by application: Crisp, but weird spacing as before
- Scaling performed by system: correct scaling, but very blurry
- Scaling performed by system: correct scaling, but very blurry

Comparison:
![Everything_tkMLC0zBsW](https://user-images.githubusercontent.com/20792748/204362893-d02443fe-c26e-4b9c-b276-1614b1b6ea2d.png)

**Comment by Darthagnon** [comment]
Blurry applications on a HiDPI screen are common; the Win8.1 scaling fix I linked earlier usually fixes them (sometimes at the cost of a couple of slightly cropped buttons), but GBM seems to be incompatible with the fix when at custom scaling factors (i.e. other than 100%)

**Comment by MikeMaximus** [comment]
This actually seems to be a bug with the split container control used on the main form.  No other form seems to have this problem.  

I'm unsure how to fix it at this point.  I'll post an update when/if I find a fix.

**Comment by MikeMaximus** [comment]
I believe I have a work-around for the issue.  It should make the main form scale properly using the "Application" High DPI scaling override and your custom scaling fix.

Try this build, just rename your GBM.exe and extract the one in this archive to the folder.  [GBM - DPI Scaling Fix.zip](https://github.com/MikeMaximus/gbm/files/10114872/GBM.-.DPI.Scaling.Fix.zip)

Let me know how it works for you.

**Comment by Darthagnon** [comment]
Works! Looks a little wider than "normal", but it scales correctly with both the DPI fix (and is non-blurry) or without (scales correctly, but is blurry (Windows bug))
![Zjw3Vvprt1](https://user-images.githubusercontent.com/20792748/204937754-c598a7e8-e5a7-4bf1-892d-05608a44c8f5.jpg)

**Comment by MikeMaximus** [comment]
Awesome 👍 Let me know if you see any other problems with DPI scaling and reopen the issue (the commit is going to auto-close it).

**Comment by MikeMaximus** [comment]
> Not sure if it's just perception and warped memory that's telling me it's a bit wider than normal, but generally, seems to be fixed! ![GBM_ofM1DshdJG](https://user-images.githubusercontent.com/20792748/204938279-ee912cdb-ca57-4d6b-be9a-bba791fdf438.png)

Sorry I didn't notice this before.  I think that is normal, it will get wider and weirder looking the higher the scaling is because the controls and window will keep growing with the font size and pushing it to the right.

**Comment by Darthagnon** [comment]
To be honest, I wasn't 100% sure if it wasn't just my memory.

Thank you, once again, for the software and continued fixes! Wishing you a Merry Christmas!
