### ISSUE TITLE
Feature suggestion: Start/Close GBM to tray

### ISSUE THREAD

**Issue by laribA** [MikeMaximus/gbm#298]
I believe that in Windows, there is an option to have the GBM window disappear and only show in the system tray when clicking the X ("close") button, as well as having GBM start only in the system tray, without opening any windows. I do not see this feature in the Linux version.
It would be much appreciated if a feature could be implemented so that GBM starts without opening any windows, and only shows in the system tray, as well as this behavior when closing.

**Comment by MikeMaximus** [comment]
Funny you should mention that,  I fixed that just a few hours ago on a whim with 1f86a4f. 😄 

You will be able to hide the window by clicking X and have it start directly to the system tray on Linux in the next release.

**Comment by laribA** [comment]
Wow. Well, that's convenient! Thanks for the fix!

Also, somewhat unrelated, but hats off to you for being a developer of open-source software. Your work is not unappreciated!
