### ISSUE TITLE
Game metadata not displayed consistently?

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#308]
I was going through my game metadata, and noticed that `Company Name` and `Version` aren't displayed for games that have those fields filled in, but are present for games with those fields empty (not sure where the metadata is being pulled from?). See screenshots:

![explorer_240324_29](https://github.com/MikeMaximus/gbm/assets/20792748/24d6e7af-9ef3-4374-9e55-fc5cda1ca4ac)

![chrome_240324_30](https://github.com/MikeMaximus/gbm/assets/20792748/d4e89a94-7e46-47eb-b274-d8ae59de0d9d)

Would it be possible to make the version number and company metadata searchable, too, similar to tags?

**Comment by Darthagnon** [comment]
I just noticed that comments don't display on the main window - would it be possible to add an option under `Settings` >> `User Interface` >> `Main Window Options` to toggle display of a `textbox with the game comment`, and `version/company info`?

**Comment by MikeMaximus** [comment]
The version and company name are pulled from the executable at the time of detection.

GBM doesn't save the detected company or version information in the game entry.  Those fields allow you to overwrite what is displayed if the publisher didn't set it or set it incorrectly.  If they are blank GBM displays the data from the executable.

Those are fields are searchable if you use the custom filter in the Game Manager.  I can see about adding them to the quick filter.

**Comment by MikeMaximus** [comment]
Sorry but I decided I don't want to make any layout changes to the UI at this point.   

But all the UI suggestions will be taken into account when/if I port GBM to another platform.
