### ISSUE TITLE
Import game from ludosavi manifests hangs

### ISSUE THREAD

**Issue by s0rl0v** [MikeMaximus/gbm#311]
Hello @MikeMaximus 

Thank you for the wornderful tool - it saved my time multiple times, especially with the older games that prone to crashing and save corruption.

Recently I wanted to import a new title from ludosavi manifests, however the app just shows inifinite spinning bar, resource consumption is at 0%:

![Screenshot 2024-09-11 143011](https://github.com/user-attachments/assets/4e50c994-e604-444b-aa6b-afc655518e88)

Could you advise what could it be and how I can fix it?
Thank you.

**Comment by MikeMaximus** [comment]
Hi there @s0rl0v

Sorry to hear you're having trouble.  I just tested it myself and it still behaves as expected.  

It is likely failing to start or complete the download of the manifest file, which is now roughly 15MB.  

First thing to check is if your firewall software is blocking GBM.

If it's not your firewall then try this:

1.  Browse to `C:\Users\<user name>\AppData\Local\gbm`
3.  Delete manifest.yaml and manifest.etag
4.  Try again.

If you still have the same problem, see if you can successfully download the manifest manually on your internet connection.

https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml

If that works, you can save it to C:\Users\<user name>\AppData\Local\gbm and then try again.

**Comment by s0rl0v** [comment]
Thank you for the quick response @MikeMaximus
Indeed, it was network issue. I retried the import and it worked after I waited ~ 10 minutes.
I will try the manual download method next time, thank you!
