### ISSUE TITLE
Start with Windows setting is on, but GBM isn't starting with Windows. 

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#5]
This happens when the location of the GBM executable changes.  I need to re-design how this setting is checked.

Use the following work-around for now:

Open the Settings, untick "Start with Windows", then click Save. Open the Settings again, tick "Start with Windows" then click Save.

**Comment by MikeMaximus** [comment]
This setting is now verified against the registry when GBM is launched and updated accordingly.  

The user is informed via notification when this occurs.

**Comment by lazycrypt** [comment]
Necroing this issue since I can't get Start with Windows to work with GBM 1.0.5 (Win10x64).

I've tried the workaround listed here as well as [this solution](https://support.microsoft.com/en-us/help/4026268/windows-change-startup-apps-in-windows-10) but neither work.

I have GBM to run as administrator if that changes anything.

**Comment by MikeMaximus** [comment]
Sorry running on startup as administrator will not work with the method GBM uses.  This is mostly a security feature of Windows.  Apps that want to run as admin on startup need to use the task scheduler. Which isnt even that well documented by Microsoft, I found that out myself when I had the same issue with another app.  The only workaround currently will be to manually create a task to start GBM as admin or turn off run as admin.

**Comment by MikeMaximus** [comment]
I'll look into using the task scheduler method for 1.0.6.

**Comment by MikeMaximus** [comment]
I spent a good amount of time looking into this and experimenting.

Unfortunately I found that adding the task scheduler method for startup will add too much extra complexity, testing and bloat for one feature.  The managed DLL just to work with the task scheduler is nearly 30% of GBM's total size.

I will add a section to the [manual](http://mikemaximus.github.io/gbm-web/manual.html) that details how to setup a task manually for anyone that wants to run GBM as administrator on Windows startup.

**Comment by lazycrypt** [comment]
It seems [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming) runs on start up as admin by adding itself in the Task Scheduler as well. I've manually added GBM and set it to run with highest priviliges. Might be worth disabling the Start with Windows option when running as Admin and/or adding a note/tooltip saying the option is not available (for now).

**Comment by MikeMaximus** [comment]
I can do that to reduce confusion as to why it won't run on startup.

Can I ask why you need GBM running as admin on startup? Do you play a lot of older games that require admin mode for proper detection?

**Comment by lazycrypt** [comment]
Yeah, I mostly use GBM for GOG games and since some require admin priviliges for compatibility GBM won't detect them otherwise. Of the top of the head Divine Divinity is one such game that needs to be ran as admin.

**Comment by MikeMaximus** [comment]
Thanks,  I thought I might be missing some other reason.  

I may take a look at this again with 1.1, which is going to overhaul a lot of other features.  But it's just not something I want to do with the current branch.
