### ISSUE TITLE
Unexpected error when starting application on Windows 7 64 bit

### ISSUE THREAD

**Issue by ShengYun** [MikeMaximus/gbm#69]
![screen shot 2017-02-16 at 4 53 23 pm](https://cloud.githubusercontent.com/assets/1317203/23042905/7b56016a-f468-11e6-9137-33c038f6911b.png)

Is GBM not supported on Windows 7?

**Comment by MikeMaximus** [comment]
That error occurs when required dll files are missing from the program folder.  Extract the package again and make sure you select all the files.

**Comment by ShengYun** [comment]
WOW! Thanks for the quick response.

![screen shot 2017-02-16 at 5 22 47 pm](https://cloud.githubusercontent.com/assets/1317203/23044070/a00f74d8-f46c-11e6-8534-a409b1a3d7f6.png)

Are there any files missing?

**Comment by MikeMaximus** [comment]
No problem.  I just happened to me looking at my phone when you posted. :) 

It looks like everything is there.  It's still crashing with the same error?

**Comment by ShengYun** [comment]
Yes it is still crashing...

**Comment by MikeMaximus** [comment]
Alrighty, I'm not sure what's wrong then.  Where do you have the GBM folder located?

**Comment by ShengYun** [comment]
One thing is I'm running this on a virtual machine and the dropbox folder is actually a network drive mapped on my host machine. Is that a problem?

**Comment by MikeMaximus** [comment]
The issue possibly is related to the VM,  but i'm not sure why.  I admit I haven't done any testing on Windows 7 in the last year, but nothing with the development requirements have changed since I started the project.

I found a possible reason,  but it's a reach. :)  Please give this test build a try.  Just extract the exe to the same folder.

http://mikemaximus.github.io/gbm-web/GBM%20Error%20Test.7z

**Comment by ShengYun** [comment]
I replaced the binary in the folder, but the error is still there...

**Comment by ShengYun** [comment]
Not sure if the following message helps, I get it by ignoring the error and continue then click on any item in the menu.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeInitializationException: The type initializer for 'GBM.mgrPath' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Mono.Data.Sqlite.SqliteConvert' threw an exception. ---> System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.CompilerServices.RuntimeHelpers.InitializeArray(Array array, RuntimeFieldHandle fldHandle)
   at Mono.Data.Sqlite.SqliteConvert..cctor()
   --- End of inner exception stack trace ---
   at Mono.Data.Sqlite.SQLite3.Open(String strFilename, SQLiteOpenFlagsEnum flags, Int32 maxPoolSize, Boolean usePool)
   at Mono.Data.Sqlite.SqliteConnection.Open()
   at GBM.mgrSQLite.Connect()
   at GBM.mgrSQLite.ReadParamData(String sSQL, Hashtable hshParams)
   at GBM.mgrVariables.ReadVariables()
   at GBM.mgrPath..cctor()
   --- End of inner exception stack trace ---
   at GBM.mgrPath.get_DatabaseLocation()
   at GBM.mgrSQLite..ctor(Database eSelectDB)
   at GBM.mgrTags.ReadTags(Database iSelectDB)
   at GBM.frmTags.LoadData()
   at GBM.frmTags.frmTags_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
GBM
    Assembly Version: 1.0.0.33789
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/shengy/GBM.v1.0.64-bit/GBM.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Mono.Data.Sqlite
    Assembly Version: 4.0.0.0
    Win32 Version: 1.0.61.0
    CodeBase: file:///C:/shengy/GBM.v1.0.64-bit/Mono.Data.Sqlite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by MikeMaximus** [comment]
The change I made was a long shot, but doesn't hurt to try. :) 

I'm not sure what else to do at this point.  

You can try resetting the app by deleting "C:\Users\*your user name*\AppData\Local\gbm" if it exists.

Just a couple questions as well that may help me figure out what's wrong.

1.  What exact version of Windows 7 are you running? (you can use "winver" in the start menu run command)
2.  What version(s) of .NET are installed?
3.  Has it ever successfully run or was there always an error message?

**Comment by ShengYun** [comment]
> 1. What exact version of Windows 7 are you running? (you can use "winver" in the start menu run command)

Windows7 Professional Version 6.1 Build 7601: Service Pack 1

> 2. What version(s) of .NET are installed?

I wasn't sure since when I saw this question I just got Visual Studio Community installed, and the error behavior changed...

3. Has it ever successfully run or was there always an error message?
No, it never ran on my Windows7, but it works on my WIndows 10

**Comment by ShengYun** [comment]
OK so I just got Visual Studio Community installed, and the new error message is:

![screen shot 2017-02-16 at 9 59 24 pm](https://cloud.githubusercontent.com/assets/1317203/23050918/454a5f96-f493-11e6-8c88-e256236d3827.png)

Then the same old one

![screen shot 2017-02-16 at 9 59 30 pm](https://cloud.githubusercontent.com/assets/1317203/23050922/4b891b04-f493-11e6-8021-9ba9f05386e0.png)

**Comment by MikeMaximus** [comment]
It looks like the main database is empty or isn't being created properly.  Did you try deleting the settings folder I mentioned?

I'm currently installing Win7 in a VM to see if I can replicate.

**Comment by ShengYun** [comment]
Deleted the folder worked... But I am suspecting it's because I installed the whole Visual Studio Community so .NET got upgraded.

Thanks for the quick response! Really awesome tool you made :) 👍

**Comment by MikeMaximus** [comment]
Nice! 

Weird that it even got far enough to attempt a database creation then fail out due to outdated .NET, but glad it's working. Enjoy :)
