### ISSUE TITLE
Add option to add more game executable

### ISSUE THREAD

**Issue by xKeiro** [MikeMaximus/gbm#74]
Some games have multiple executables mainly because they have different executable for different directX modes. (example: ffxiv.exe | ffxiv_dx11.exe)

**Comment by MikeMaximus** [comment]
You can handle this currently by just creating a duplicate configuration for each executable.  As long as the name of the game is the same for each one, they will all use the same backup data.

It is kinda clunky I admit.  

The app needs a database design overhaul.  Once I get to that i'll also allow one configuration to have multiple executables.

**Comment by MikeMaximus** [comment]
I'm going to push this off and do it when I get to porting to C#.

The database changes I want to make for this feature would require rewriting at least 1/3 of the application and re-testing every aspect.

**Comment by MikeMaximus** [comment]
Multiple executables will be handled by the new regular expressions feature (#98), the multiple configuration method I detailed above will also still work.
