### ISSUE TITLE
Add an optional extra step to Add Game Wizard.... additonal file

### ISSUE THREAD

**Issue by Kusaha** [MikeMaximus/gbm#75]
If somebodys game database grows quite large (or if you ever to introduce crowd sourced game saves) there may be conflict in the game detection with the currenct system, because two games could have the same executable names. 

Adding an extra step to the Add Game Wizard that requires you to select another game file (related to the executable) would eleminate this type of conflicts. 

Here's a great example of a program using this method (evolve): 
https://www.evolvehq.com/guides/gamesdb-rules

-------
So when a game executable detected gbm should check if the previously mentioned file is present before it starts monitoring the game.

**Comment by MikeMaximus** [comment]
GBM already handles those conflicts by using the executable path.  If the path information is not available it will ask the user to identify the game once they quit their session and store the path for future use.

Evolve's method is interesting though, something to think about possibly changing.
