### ISSUE TITLE
Game Database Export - Save location not saved

### ISSUE THREAD

**Issue by Kusaha** [MikeMaximus/gbm#76]
When you try to export your game database after clicking the "Export" button GBM always offers to save the file to Documents, instead of your last selected file location. 

Personally I'd recommend adding an option in the settings to designate the default Game Database export location or just simply tell the program to remember your last selected location.

---------
Other: Honestly I love how GBM automatize things and it feels quite odd that you have to manually save your modified game database everytime you add a game, personally I'd love to have the option to automatically export the database after adding a new game.

**Comment by Kusaha** [comment]
Ohh could you tell me how can I restore the database from the automatically created files then?

**Comment by MikeMaximus** [comment]
Not really sure what you're asking.

The gbm.s3db file in the location I specified stores all settings and game configuration data as you use the app.  There's no need to ever manually save to it or restore from it.  If you want to make a copy of your game configurations to share or as a backup, that's when the Export & Import features are used.

**Comment by Kusaha** [comment]
Oh I see. Though that's the point, it's odd that you are using the software to manually back game saves up but you have to manually import your gbm database in order to be able to restore it later or share it.

**Comment by MikeMaximus** [comment]
I'm just not understanding why you'd want to do an export every time you add a new game.

Why not just add a whole batch of game configurations, then do a single export when you're done?

**Comment by Kusaha** [comment]
That's what I'm doing at the moment, but i'd much prefer if this was an automated process, since the whole purpose of the program is to automatize things. (or at least for me) And this is why I said that it would be nice if it could do a save everytime you make a change to the database (adding a game, changing save location etc). I get it does this now as well but you can't restore the settings without exporting it. So why not make it restoreable by default? So you wont have to worry about manually exporting the database everytime you make a slight change to something.

**Comment by MikeMaximus** [comment]
So if I'm understanding this, you want an option to automatically make an XML export of your configurations to a specific location each time you make a change?

**Comment by Kusaha** [comment]
Yes. Either that or a way to import .s3db files, whicever works.

**Comment by MikeMaximus** [comment]
It shouldn't be too difficult to add an option to automatically export an xml file in the next version.  It just seems a little redundant to me because of the following.  

When you add a game configuration or make a change the following happens:

1.  The data is saved to the local database
2.  If syncing is enabled (it's on by default), the data is also saved to the master database in your backup folder.

If you happen to ever lose the local data,  it will be automatically restored from the master s3db in the backup folder.  So the only time you ever really need an XML backup is if you'd somehow lose both.

**Comment by Kusaha** [comment]
Sorry for the late reaction it was super late, and wanted to check something before writing another comment. So I installed GBM on my laptop and selected the same one drive folder that i'm using on my main computer and it restored the game database without an issue without the need of the XML file, so yeah you may be right about that it is not necessary to implement an auto XML backup option, though the two reasons why I thought that this .s3db methound wouldn't work are the follows:
- last time when I had to reinstall GBM I lost my customized database (most likely because at the initial startup wizard I clicked on the import official database)
- there was really no indications in GBM that it could automatically restore databases (or at least I wasn't aware), but there's a clear indications of XML import/export option, so I naturally thought that was the way to go

--------------
Nevertheless the main reason I opened the topic still stands, that it would be nice to be able to designate a default location for the XML export or at least to remember to the last saved location. 

Thanks for your hard work
Keep it up!

**Comment by MikeMaximus** [comment]
Ah I understand.  It's odd that it wasn't able to restore the last time you re-installed, the final options in the wizard shouldn't affect that.

And yeah we got a little off track!  I always did agree with the main topic,  I was just confused by your auto-export addendum. 

There's a few places where it should remember the last browse/save folder so I may just implement that across the whole app.  Thanks for your suggestions.

**Comment by MikeMaximus** [comment]
GBM will now remember the last browse/save location in all areas where it makes sense to do so.
