### ISSUE TITLE
Support detection of command parameters

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#79]
This would be practical for all games which use interpreters, VMs, emulators or just share the engine with others.
Ideally this behavior would be enabled via an additional text input box. Stating the interpreter and the game together, would then also be allowed.

* `shattered-pixel-dungeon.jar` should match on `java -jar /usr/share/shattered-pixel-dungeon/shattered-pixel-dungeon.jar`
* `mrrescue-1.02e.love` should match on `love /usr/share/mrrescue/mrrescue-1.02e.love`
* `solarus-run` and `zsdx` should match on `solarus-run /usr/share/solarus/zsdx`
* `ardentryst.py` should match on `python2 ardentryst.py`

**Comment by MikeMaximus** [comment]
The capability to detect parameters is already there for detecting games running in Wine, so it shouldn't be too hard to add this feature as well.

**Comment by MikeMaximus** [comment]
I couldn't do this exactly as described.

GBM can now match on any part of a supplied parameter, but it can't match on only the parameter, the interpreter/process is always required.

Using your examples:
- java shattered-pixel-dungeon.jar will match on java -jar /usr/share/shattered-pixel-dungeon/shattered-pixel-dungeon.jar
- love mrrescue-1.02e.love will match on love /usr/share/mrrescue/mrrescue-1.02e.love
- solarus-run zsdx will match on solarus-run /usr/share/solarus/zsdx
- python2 ardentryst.py will match on python2 ardentryst.py

**Comment by basxto** [comment]
I suggested this because some linux distributions use python/python3 and others use python2/python as executables for python 2 and 3.
But this will solve itself when it is allowed to specify multiple executables

**Comment by MikeMaximus** [comment]
Ah I see,  well this should still be handy for a few other situations
