### ISSUE TITLE
Navigating through game list broken in game manager

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#80]
When you navigate with up and down keys through the list of games, the first element will be toggled each time you press those keys.
This means that two games are selected on every second key press.

Distribution: Archlinux
Kernel: 4.11.3
mono: 5.0.0.100
mono-basic: 4.6
p7zip: 16.02
sqlite: 3.19.3
bash: 4.4.012

**Comment by MikeMaximus** [comment]
I noticed this when I was porting it to run on Mono initially.  

I'll confirm it again, but believe it's a bug with Mono's implementation of that control, there's a few niggling issues like that.

**Comment by MikeMaximus** [comment]
I tracked down what causes this annoying bug.  

Mono's listbox control does this when it's filled with using the DataSource property.

GBM now populates the listbox on Linux using a method that won't trigger this behavior.
