### ISSUE TITLE
Wrong tags displayed after adding new game

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#81]
Immediately after pressing “Save” on a new game, it could show wrong tags or rather tags of another game. When you open the tag configuration via “Tags…”, no current tags are listed.
It further seems a bit odd, that you are only allowed to add tags after the game got saved, but I suppose that has to do with the underlying structure of the database.

Distribution: Archlinux
Kernel: 4.11.3
mono: 5.0.0.100
mono-basic: 4.6
p7zip: 16.02
sqlite: 3.19.3
bash: 4.4.012

**Comment by MikeMaximus** [comment]
I'm having trouble replicating this.  I tried adding a few games in a row with various tags and had no issues.  My VM has a older version of Mono however.  I'll take a further look into it when I get around to working on this.

The way it functions is due to database structure yes, but mostly to me being lazy.

**Comment by basxto** [comment]
Yes, had trouble to reproduce it myself.
But now I found the culprit and get that behavior every time:
* use a custom tag filter
* select a game with tags
* add a new game
* save
* new game shows the tags from the previous selected game

The new game did not qualify for the filter, that is probably relevant.

**Comment by MikeMaximus** [comment]
Ok confirmed.  Thanks for the detailed steps.

**Comment by MikeMaximus** [comment]
When an add/edit occurs that doesn't match the current filter, the Game Manager will go into disabled mode like it's supposed to, instead of showing possibly incorrect data.

You can now add tags when adding a new configuration,  you no longer need to save first.
