### ISSUE TITLE
Support setting a custom root path

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#83]
For old PCs, old backups etc. it could be useful to search for existing gamesaves and offer to to import them. Or just to report them with their paths.

Maybe offering a complete search for all know games could be nice for freshly installed versions of GBM. You don’t have necessarily all games still installed, you ever played.

**Comment by MikeMaximus** [comment]
I've toyed with that idea,  it just keeps dropping to the bottom of the priority list though. :)

**Comment by MikeMaximus** [comment]
The import screen will now detect most existing saved games, then tick those configurations for import automatically.  Only configurations using an absolute saved game path are detected, which is the vast majority of them.  

Trying to detect relative path configurations adds so much extra complexity for little value so it's not something I want do, at least not right now.  I have some plans to enhance the wizard on fresh installs, so I may re-visit it.
