### ISSUE TITLE
Placeholders in paths

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#84]
Placeholders like `*` would be nice, since some FLOSS games include their version in the main folder:
```
~/.warsow-1.0
~/.warzone2100-3.1
~/.warzone2100-3.2
```

**Comment by MikeMaximus** [comment]
You can use place holders like * or ? in the include or exclude.

Set the save path as the home folder and try .warzone* for an include?

Let me know if there's issues with that.

**Comment by basxto** [comment]
I have tried that, it might work, but not in an acceptable amount of time.
I killed GBM after a couple of minutes.
I guess matching 630 files directly in my home folder and matching 1.5 million files in my whole home folder make a huge difference

Get the include/exclude patterns directly forwarded to 7za?

**Comment by MikeMaximus** [comment]
The include / exclude builder is choking on your home folder? That thing has been a pain to get working well in mono.

What I'll do is allow a raw edit of the include and exclude from the game manager directly like it was in past versions..  Its just a colon delimited list.

**Comment by MikeMaximus** [comment]
Where exactly is this happening?  

When you trying to setup the includes on the Include Builder or during the actual backup process?

GBM builds a text file with the patterns and gives it to 7za.

**Comment by basxto** [comment]
It happens when I start the backup, so it is probably 7za which is having a hard time.
I also defined many excludes.

**Comment by MikeMaximus** [comment]
Let me know how it goes.  Can you attach an example of the configuration?

**Comment by basxto** [comment]
I cannot reproduce it on terminal, 7za throws an error because it does not have permission to open a folder, but that should result in an error.

**Comment by MikeMaximus** [comment]
Yes, once 7za ends GBM should just report back with a generic failure.

You can take a look at .~/local/share/gbm and see if the include/exclude files being passed to 7za are being created correctly.

**Comment by basxto** [comment]
There must be a deeper issue, those two files do not get written, they still have the values from the last backup.
```
Process:  warzone2100
Save Path: /home/dabascht/
Include: .warzone2100-*
Exclude: logs:maps:mods:multiplay:music:screenshots:userdata:config:*.map
```

It says `A manual backup of Warzone 2100 was triggered.` and freezes.

Oh, the disk size calculator might be it … combined with my 500GB home directory. It is also possible that there are circular links, which is allowed and shouldn’t be a problem.

**Comment by MikeMaximus** [comment]
Yeah it's the disk size calculator, it needs to be redesigned to handle situations like this.  I may have a commit up later you can try.

**Comment by MikeMaximus** [comment]
Please give the latest commit a try when you get a moment.  

It might pause a little while, but it should no longer get stuck.   

Right now it's not handling include/excludes properly so it's just reporting the full size of the entire save path.  I'm still working on that.

**Comment by MikeMaximus** [comment]
I'm going to assume this is working based on my testing and do the release on schedule. 

If something is still broken I'll do a hot fix.
