### ISSUE TITLE
Fix some defects  found by gendarme 

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#85]
Gandarme is the application / library analysis tool of the mono project. I think most defects can be ignored, since it analyzes the whole GBM.exe and that means those defects can be in the used libraries.
Especially [Gendarme.Rules.Portability.MonoCompatibilityReviewRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Portability.MonoCompatibilityReviewRule(2.10)) should improve compiling gbm with mono. 

`Microsoft.VisualBasic.MyServices` and `Microsoft.VisualBasic.CompilerServices` is completely missing

```
System.Int32 Microsoft.VisualBasic.CompilerServices.Operators::CompareString(System.String,System.String,System.Boolean) is missing from Mono
System.String Microsoft.VisualBasic.CompilerServices.Conversions::ToString(System.Int32) is missing from Mono
System.Void Microsoft.VisualBasic.FileSystem::Rename(System.String,System.String) is missing from Mono.
 System.Object Microsoft.VisualBasic.CompilerServices.NewLateBinding::LateGet(System.Object,System.Type,System.String,System.Object[],System.String[],System.Type[],System.Boolean[]) is missing from Mono.
System.Boolean Microsoft.VisualBasic.CompilerServices.Operators::ConditionalCompareObjectEqual(System.Object,System.Object,System.Boolean) is missing from Mono.
System.Void Microsoft.VisualBasic.CompilerServices.ProjectData::SetProjectError(System.Exception) is missing from Mono.
System.Void Microsoft.VisualBasic.CompilerServices.ProjectData::ClearProjectError() is missing from Mono.
Microsoft.VisualBasic.MyServices.FileSystemProxy Microsoft.VisualBasic.Devices.ServerComputer::get_FileSystem() is missing from Mono.
System.Collections.ObjectModel.ReadOnlyCollection`1<System.IO.DriveInfo> Microsoft.VisualBasic.MyServices.FileSystemProxy::get_Drives() is missing from Mono.
System.Int32 Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(System.Object) is missing from Mono.
System.Object Microsoft.VisualBasic.CompilerServices.Operators::AndObject(System.Object,System.Object) is missing from Mono.
System.Boolean Microsoft.VisualBasic.CompilerServices.Conversions::ToBoolean(System.Object) is missing from Mono.
System.String Microsoft.VisualBasic.Interaction::InputBox(System.String,System.String,System.String,System.Int32,System.Int32) is missing from Mono.
System.Void System.Windows.Forms.LinkLabel::set_TabStop(System.Boolean) is missing from Mono.
System.Type System.Type::GetTypeFromCLSID(System.Guid) is not implemented.
System.Type System.Type::GetTypeFromCLSID(System.Guid) is marked with a [MonoTODO] attribute: This operation is currently not supported by Mono.
System.DateTime Microsoft.VisualBasic.DateAndTime::get_TimeOfDay() is missing from Mono.
System.Boolean Microsoft.VisualBasic.CompilerServices.Operators::ConditionalCompareObjectNotEqual(System.Object,System.Object,System.Boolean) is missing from Mono.
System.Drawing.Icon System.Drawing.Icon::ExtractAssociatedIcon(System.String) is marked with a [MonoTODO] attribute: The same icon, SystemIcons.WinLogo, is returned for all file types.
System.Reflection.ProcessorArchitecture System.Reflection.AssemblyName::get_ProcessorArchitecture() is marked with a [MonoTODO] attribute: Not used, as the values are too limited; Mono supports more.
Microsoft.VisualBasic.ApplicationServices.AssemblyInfo Microsoft.VisualBasic.ApplicationServices.ApplicationBase::get_Info() is missing from Mono.
System.Version Microsoft.VisualBasic.ApplicationServices.AssemblyInfo::get_Version() is missing from Mono.
Microsoft.VisualBasic.ApplicationServices.AssemblyInfo Microsoft.VisualBasic.ApplicationServices.ApplicationBase::get_Info() is missing from Mono.
System.Char Microsoft.VisualBasic.Strings::Chr(System.Int32) is missing from Mono.
System.DateTime Microsoft.VisualBasic.DateAndTime::get_Now() is missing from Mono.
System.Void Microsoft.VisualBasic.CompilerServices.NewLateBinding::LateSet(System.Object,System.Type,System.String,System.Object[],System.String[],System.Type[]) is missing from Mono.
System.Int64 Microsoft.VisualBasic.DateAndTime::DateDiff(Microsoft.VisualBasic.DateInterval,System.DateTime,System.DateTime,Microsoft.VisualBasic.FirstDayOfWeek,Microsoft.VisualBasic.FirstWeekOfYear) is missing from Mono.
System.DateTime Microsoft.VisualBasic.DateAndTime::DateAdd(Microsoft.VisualBasic.DateInterval,System.Double,System.DateTime) is missing from Mono.
Microsoft.VisualBasic.MyServices.FileSystemProxy Microsoft.VisualBasic.Devices.ServerComputer::get_FileSystem() is missing from Mono.
System.Void Microsoft.VisualBasic.MyServices.FileSystemProxy::DeleteFile(System.String,Microsoft.VisualBasic.FileIO.UIOption,Microsoft.VisualBasic.FileIO.RecycleOption) is missing from Mono.
System.Void Microsoft.VisualBasic.MyServices.FileSystemProxy::DeleteDirectory(System.String,Microsoft.VisualBasic.FileIO.UIOption,Microsoft.VisualBasic.FileIO.RecycleOption) is missing from Mono.
System.Int64 Microsoft.VisualBasic.CompilerServices.Conversions::ToLong(System.Object) is missing from Mono.
System.Boolean Microsoft.VisualBasic.Information::IsDBNull(System.Object) is missing from Mon
System.Double Microsoft.VisualBasic.CompilerServices.Conversions::ToDouble(System.Object) is missing from Mono.
System.Object Microsoft.VisualBasic.CompilerServices.Operators::ConcatenateObject(System.Object,System.Object) is missing from Mono.
System.Boolean Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::get_UseCompatibleTextRendering() is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::Run(System.String[]) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::.ctor(Microsoft.VisualBasic.ApplicationServices.AuthenticationMode) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::set_IsSingleInstance(System.Boolean) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::set_EnableVisualStyles(System.Boolean) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::set_SaveMySettingsOnExit(System.Boolean) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::set_ShutdownStyle(Microsoft.VisualBasic.ApplicationServices.ShutdownMode) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::set_MainForm(System.Windows.Forms.Form) is missing from Mono.
System.Boolean Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::get_SaveMySettingsOnExit() is missing from Mono.
System.Void Microsoft.VisualBasic.CompilerServices.ObjectFlowControl::CheckForSyncLockOnValueType(System.Object) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler::.ctor(System.Object,System.IntPtr) is missing from Mono.
System.Void Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::add_Shutdown(Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler) is missing from Mono.
System.Void Microsoft.VisualBasic.Devices.Computer::.ctor() is missing from Mono.
System.String Microsoft.VisualBasic.CompilerServices.Utils::GetResourceString(System.String,System.String[]) is missing from Mono.
```

---

[Gendarme](http://www.mono-project.com/docs/tools+libraries/tools/gendarme/) found 5698 potential defects using 235 rules.
Assembly:
* [Gendarme.Rules.Design.MarkAssemblyWithCLSCompliantRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.MarkAssemblyWithCLSCompliantRule(2.10)) : 1 defects
* [Gendarme.Rules.Naming.AvoidNonAlphanumericIdentifierRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Naming.AvoidNonAlphanumericIdentifierRule(2.10)) : 1 defects
* [Gendarme.Rules.Naming.UseCorrectCasingRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Naming.UseCorrectCasingRule(2.10)) : 262 defects

Type:
* [Gendarme.Rules.BadPractice.ConstructorShouldNotCallVirtualMethodsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.BadPractice.ConstructorShouldNotCallVirtualMethodsRule(2.10)) : 3023 defects
* [Gendarme.Rules.Correctness.TypesWithDisposableFieldsShouldBeDisposableRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Correctness.TypesWithDisposableFieldsShouldBeDisposableRule(2.10)) : 1 defects
* [Gendarme.Rules.Design.AvoidVisibleFieldsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.AvoidVisibleFieldsRule(2.10)) : 2 defects
* [Gendarme.Rules.Design.AvoidVisibleFieldsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.AvoidVisibleNestedTypesRule(2.10)) : 2 defects
* [Gendarme.Rules.Design.AvoidVisibleNestedTypesRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.AvoidVisibleNestedTypesRule(2.10)) : 20 defects
* [Gendarme.Rules.Design.ConsiderUsingStaticTypeRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.ConsiderUsingStaticTypeRule(2.10)) : 9 defects
* [Gendarme.Rules.Design.DeclareEventHandlersCorrectlyRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.DeclareEventHandlersCorrectlyRule(2.10)) : 17 defects
* [Gendarme.Rules.Design.DoNotDeclareSettersOnCollectionPropertiesRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.DoNotDeclareSettersOnCollectionPropertiesRule(2.10)) : 8 defects
* [Gendarme.Rules.Design.FlagsShouldNotDefineAZeroValueRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.FlagsShouldNotDefineAZeroValueRule(2.10)) : 1 defects
* [Gendarme.Rules.Design.Generic.AvoidDeclaringCustomDelegatesRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.Generic.AvoidDeclaringCustomDelegatesRule(2.10)) : 16 defects
* [Gendarme.Rules.Design.Generic.DoNotExposeGenericListsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.Generic.DoNotExposeGenericListsRule(2.10)) : 20 defects
* [Gendarme.Rules.Naming.UseSingularNameInEnumsUnlessAreFlagsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Naming.UseSingularNameInEnumsUnlessAreFlagsRule(2.10)) : 8 defects
* [Gendarme.Rules.Performance.AvoidUnsealedUninheritedInternalTypeRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.AvoidUnsealedUninheritedInternalTypeRule(2.10)) : 1 defects
* [Gendarme.Rules.Maintainability.AvoidLackOfCohesionOfMethodsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Maintainability.AvoidLackOfCohesionOfMethodsRule(2.10)) : 21 defects
* [Gendarme.Rules.Maintainability.VariableNamesShouldNotMatchFieldNamesRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Maintainability.VariableNamesShouldNotMatchFieldNamesRule(2.10)) : 1 defects

Method:
* [Gendarme.Rules.BadPractice.CheckNewThreadWithoutStartRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.BadPractice.CheckNewThreadWithoutStartRule(2.10)) : 3 defects
* [Gendarme.Rules.BadPractice.DoNotDecreaseVisibilityRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.BadPractice.DoNotDecreaseVisibilityRule(2.10)) : 482 defects
* [Gendarme.Rules.Concurrency.DoNotUseMethodImplOptionsSynchronizedRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Concurrency.DoNotUseMethodImplOptionsSynchronizedRule(2.10)) : 360 defects
* [Gendarme.Rules.Correctness.CheckParametersNullityInVisibleMethodsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Correctness.CheckParametersNullityInVisibleMethodsRule(2.10)) : 50 defects
* [Gendarme.Rules.Correctness.EnsureLocalDisposalRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Correctness.EnsureLocalDisposalRule(2.10)) : 63 defects
* [Gendarme.Rules.Correctness.ReviewDoubleAssignmentRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Correctness.ReviewDoubleAssignmentRule(2.10)) : 1 defects
* [Gendarme.Rules.Design.AvoidRefAndOutParametersRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.AvoidRefAndOutParametersRule(2.10)) : 11 defects
* [Gendarme.Rules.Design.PreferUriOverStringRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.PreferUriOverStringRule(2.10)) : 1 defects
* [Gendarme.Rules.Exceptions.DoNotThrowInNonCatchClausesRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Exceptions.DoNotThrowInNonCatchClausesRule(2.10)) : 1 defects
* [Gendarme.Rules.Exceptions.DoNotSwallowErrorsCatchingNonSpecificExceptionsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Exceptions.DoNotSwallowErrorsCatchingNonSpecificExceptionsRule(2.10)) : 34 defects
* [Gendarme.Rules.Exceptions.UseObjectDisposedExceptionRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Exceptions.UseObjectDisposedExceptionRule(2.10)) : 27 defects
* [Gendarme.Rules.Performance.AvoidRepetitiveCallsToPropertiesRule]() : 505 defects
* [Gendarme.Rules.Performance.AvoidRepetitiveCastsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.AvoidRepetitiveCastsRule(2.10)) : 88 defects
* [Gendarme.Rules.Performance.AvoidUncalledPrivateCodeRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.AvoidUncalledPrivateCodeRule(2.10)) : 7 defect
* [Gendarme.Rules.Performance.AvoidUnneededFieldInitializationRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.AvoidUnneededFieldInitializationRule(2.10)) : 49 defects
* [Gendarme.Rules.Performance.AvoidUnusedParametersRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.AvoidUnusedParametersRule(2.10)) : 1 defects
* [Gendarme.Rules.Performance.DoNotIgnoreMethodResultRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.DoNotIgnoreMethodResultRule(2.10)) : 3 defects
* [Gendarme.Rules.Performance.PreferCharOverloadRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.PreferCharOverloadRule(2.10)) : 2 defects
* [Gendarme.Rules.Performance.UseStringEmptyRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.UseStringEmptyRule(2.10)) : 6 defects
* [Gendarme.Rules.Portability.DoNotHardcodePathsRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Portability.DoNotHardcodePathsRule(2.10)) : 11 defects
* [Gendarme.Rules.Portability.MonoCompatibilityReviewRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Portability.MonoCompatibilityReviewRule(2.10)) : 506 defects
* [Gendarme.Rules.Maintainability.AvoidUnnecessarySpecializationRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Maintainability.AvoidUnnecessarySpecializationRule(2.10)) : 12 defects
* [Gendarme.Rules.Globalization.AvoidUnusedInternalResourceRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Globalization.AvoidUnusedInternalResourceRule(2.10)) : 13 defects
* [Gendarme.Rules.Globalization.PreferIFormatProviderOverrideRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Globalization.PreferIFormatProviderOverrideRule(2.10)) : 41 defects
* [Gendarme.Rules.Globalization.PreferStringComparisonOverrideRule](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Globalization.PreferStringComparisonOverrideRule(2.10)) : 9 defects

**Comment by basxto** [comment]
With `Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase::Run` missing it’s probably impossible to get it compiling on linux.

**Comment by MikeMaximus** [comment]
I don't plan to do a lot more work on GBM in it's current state.  Any new projects will have better multi-platform support.
