### ISSUE TITLE
Play time ranking

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#86]
Having a ranking for games most played all time and over a specified time span, would be really neat.

I’m aware, that you can look up play time in the Game Manager, but it’s hard to compare  games.

**Comment by MikeMaximus** [comment]
I've wanted something like this as well, I've just been unsure exactly how I want to implement it.  Maybe a way to spit out an HTML report based on a filter.

**Comment by MikeMaximus** [comment]
GBM doesn't store enough data, or store it in a way that's conducive to generating detailed reports, such as hours played over a time span.  So I decided not to design a whole new feature around this.

But I am redesigning the "Custom Filter" on the Game Manager for v1.04 to be more robust.  For example, you'll able to fully customize the sort order.

So it'll be pretty easy to compare play time on the Game Manager.  I've just been testing a prototype and it was interesting to look at my Most Played All Time over the last 2 - 3 years.  👍
