### ISSUE TITLE
Allow empty save path when monitor only

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#89]
Allow not to specify a save path when a game is set to monitor only.
This would make it also necessary to include the monitor-only option in the xml export.
Would be handy for games who have no (meaningful) save games, at least when you want to track their play time:

* casual games
* roguelikes which usually delete save games on death (permadeath)
* games which are multiplayer only

On the one hand this defeats the main purpose of gbm a bit, on the other hand it’s the only tool for play time tracking I know.

**Comment by MikeMaximus** [comment]
You should be able to do this if you tick "Save Entire Folder" with an empty path.

![monitor_only](https://user-images.githubusercontent.com/15719732/27517191-8a4b998c-5985-11e7-92d6-dd32db5efc11.jpg)

But yeah Monitor Only isn't handled very well on the configuration side.  It's something I tacked on and never implemented in the GUI properly.  I'll need to spend some time on it.

**Comment by MikeMaximus** [comment]
The following changes have been made to Monitor only:

1.  It is now part of the XML Import / Export and can be used in official configurations.
2.  When Monitor only is toggled on, configuration fields that are no longer necessary are disabled and validation on them is skipped.
3.  No existing configuration data is cleared or modified when Monitor only is toggled, so the user can freely toggle it on or off for games that have a full configuration.

**Comment by basxto** [comment]
Thank you very much, I hope I find some time and motivation soon to to upload such configurations

**Comment by MikeMaximus** [comment]
I'll be adding a few of these configurations to the Windows list the next time I do an update.  

I'll be using the tag #Tracking for these configurations if you want to use that one as well.
