### ISSUE TITLE
Support Steam AppId

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#92]
I really dislike this solution, but there are games which can’t get detected otherwise.

I have found a few games with badly named binaries so far:
* UDKGame-Linux (Antichamber and  Unmechanical) when Unreal Engine 3 is used
* runner (Stealth Bastard Deluxe, Undertale, VA-11 HALL-A) when GameMaker Studio is used

I only took a more detailed look at Antichamber so far:

Steam Version: Environment variable "SteamAppId" is set to "219890"
Humble Version: CWD contains a file "steam_appid.txt" which contains "219890"

**Comment by MikeMaximus** [comment]
When games share the same process name GBM detects them based on their path, and if it doesn't know the path yet it'll ask which game was running once it ends and store the path.

Unless i'm totally missing the issue.

**Comment by basxto** [comment]
the working directory?

**Comment by MikeMaximus** [comment]
Yes, does that solution not work with those particular games?

**Comment by basxto** [comment]
I wasn’t aware of that. Yes it does work for both.

That does explain why detection of Zelda Mystory of Solarus and other games, which are detected via parameter now, behaved so weirdly. They had the same executable and same working directory

**Comment by MikeMaximus** [comment]
Ah, yeah that situation couldn't be handled.  It would just detect whatever it seen first.
