### ISSUE TITLE
Wrong disk space on linux

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#94]
GBM uses free space of `/` instead of `/home/`

Partitions can be mounted freely into the directory tree

**Comment by MikeMaximus** [comment]
Yeah that's kind of an embarrassing oversight on my part.

I think I want to just use the df utility to get this information on Linux.

**Comment by MikeMaximus** [comment]
This should now be working with the latest commit in v103,  but I'm not sure I like the solution.  I'll continue thinking about this and see if I can come up with a nice way to do it without df.

**Comment by MikeMaximus** [comment]
I had another way to do this that doesn't rely on df.  But Mono's System.IO.DriveInfo implementation seems hit and miss when it comes to detecting network mount points, while df is always rock solid with both physical disks and network mounts.

I'm going to stick with df,  GBM already relies on other coreutils so it's probably not that big a deal.

**Comment by MikeMaximus** [comment]
This isn't working on Mint 18.3 for some reason, I think the df parse is failing.

**Comment by MikeMaximus** [comment]
I broke this when I was doing fixes #104 and #105.  

I haven't been testing releases on Linux well enough.  I'll improve on that so this stops happening.
