### ISSUE TITLE
Ignore binary extensions

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#98]
Since .exe gets ignored, maybe other executable extensions should get too?

Like .bin .run .x86 .x86_64 .bin.x86 .bin.x86_64.
The first two are those, which often are listed on file extension lists.
The latter are those, which really get used much by games.
Not distinguishing between .x86 and .x86_64 could really help with platform independency.

Better alternative is maybe to allow regex for the process name and not to ignore any extensions by default.
Instead adding `(\.exe)?` by default for Windows and `(\.(exe|run|elf|bin])?(\.(x86(_64)?|(amd|x)64))?` for Linux.

**Comment by basxto** [comment]
Making it explicit is probably impractical for Windows.
But regex would still be good, since different distribution platforms can use different executable names, but compatible savegames.

**Comment by MikeMaximus** [comment]
I'll see what I can do.  A regex type solution would be useful.

**Comment by basxto** [comment]
In Python I use the `re.search` function with `self.process + binaryExtension + '$'` and `self.argument + '$'`.

https://msdn.microsoft.com/en-us/library/twcw2f1c(v=vs.110).aspx should work similarly

```
Dim processRe As Regex = new Regex(process & '(\.(exe|run|elf|bin))?(\.(x86(_64)?|(amd|x)64))?$')
If processRe.Match(realProcessName).Success Then
  <found>
Else
 <continue searching>
End If
```
That could do the job

**Comment by basxto** [comment]
It would be confusing for a regular user, I think.
We would either need a check box for activating Regex or escape regex syntax by default and offer a raw edit dialog for writing regex.
`.` is probably the only regex symbol regular users will use, but your application could get trouble with `:`, since I noticed you usually drop that sign instead of escaping it.

---

It seems `isMatch()` is better than `.Match().Success`

**Comment by MikeMaximus** [comment]
I like this, but honestly GBM's detection code is just a mess.  

I need to put aside a day and to rewrite the entire thing so I can properly add new features like this.

I'm adding this to a v1.1 milestone.  It's going to get done, I just don't know when.

**Comment by basxto** [comment]
It’s getting more important, since I have to track the executable `python2.7` for Ardentryst and Unknown Horizons now.

2.7 will be last 2.x version, that is not the problem, but it is likely named `python` on Ubuntu.

Heterogenity is always to be expected on linux, since the way of distributing games is heterogen.

**Comment by basxto** [comment]
Using regex would also fix #74

**Comment by MikeMaximus** [comment]
Yeah it will, I thought about doing both because I never did really like how I structured the db.  But I don't think i'm going to do that, it just cascades into a ridiculous amount of changes and testing.

I'm going to redo a portion of the detection code to add regex support.

**Comment by MikeMaximus** [comment]
So this was easier to implement than I thought, not sure what put me off when I looked into it before.

Here is how I currently have it working:

- Game configurations now have a "Regular Expression" checkbox.
- When the checkbox is enabled, GBM will match based on the provided RegEx in the Process field.
- When the checkbox is disabled. GBM will try for an exact match of the process name like it does now.
- I decided against ignoring any other extensions by default.  As you said it would be confusing, unless I put the default rules on the form itself.

I've been testing it and it's actually working quite well.  My only concern is CPU usage spikes are now visible when GBM is in scan mode, while the old code didn't even register usage.  So I want to see what I can do about that.

I'll be doing a pre-release after I get this finalized.

**Comment by MikeMaximus** [comment]
I think the CPU and memory usage are in a good place now.  The more regex configurations it has to process per scan cycle the greater the impact, there's no way around that.  But it's quite minimal even with hundreds of regex configurations.

I also added some validation and help.  GBM will offer to take you to regexr.com when validation fails.  I haven't done much testing on Linux yet, hopefully there's nothing wonky on that end.

**Comment by basxto** [comment]
I’ve played around with regex on the prerelease a bit, it’s working pretty good.
My favorites are:
* Amnesia The Dark descent `Amnesia(_NO_STEAM)?\.bin\.x86(_64)?`
* Unepic `unepic(32|64)(gog|s)`
* Xonotic `xonotic-(glx|sdl)`

But there is one issue, it looks like it breaks detection of games with ambiguous process names

**Comment by basxto** [comment]
The regex flag does not get exported:

basxto/gbm-web@fc09fce0683cfee46988508949d1a253a2be6ffb

**Comment by MikeMaximus** [comment]
Thanks for giving it a test run basxto.  

Can you give me an example of a process that's not getting detected?

I see the IsRegEx field in your export.

**Comment by basxto** [comment]
I have a few games with the process `runner` and I renamed one into `runn?er`, this one did not appear in the list any longer. I also deleted known paths to force gbm to ask which game has just run.

**Comment by MikeMaximus** [comment]
Thanks,  I see what the issue is now. 👍 

No worries with the regex flag.  I have forgotten the export before, it surprised me that it was actually there.

**Comment by MikeMaximus** [comment]
Regex patterns that match another process are now considered duplicates and will appear in the list.  I'm a little wary of the fix, but I think it'll be ok.

I'll wait to see what else might come up and update the prerelease this weekend.

**Comment by MikeMaximus** [comment]
Another issue was that a process with a parameter and a regex pattern matching the same process with the same parameter wasn't being considered a duplicate.  My fixes from last night also could cause crashes in some situations, hopefully my new coffee fuelled fixes turn out better.
