### ISSUE TITLE
Store sessions

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#99]
```sql
CREATE TABLE `session` (
	`MonitorID`	INTEGER NOT NULL,
	`Start`	INTEGER NOT NULL,
	`End`	INTEGER NOT NULL,
	PRIMARY KEY(`MonitorID`,`Start`)
);
```
I’d propose to use the Unix Time format, which is seconds passed since 1970-01-01.
It does not have to get used immediately, just storing would be nice. As soon as it gets used some statistically data is already available.
You could also store whether the backup was successful and maybe the used backup path.

**Comment by MikeMaximus** [comment]
I'll add the table and store the data starting in v1.05.

I'm thinking of a spreadsheet type history screen to view the data, with filter options.

**Comment by MikeMaximus** [comment]
I was thinking about storing the the backup status and path with session.  But would that data be useful for statistics?  A backup failing should be very rare and the path would be static for most configurations.

I am storing the PC name with the session so you can track which PC that session was played on.

**Comment by basxto** [comment]
Storing executable path could be interesting, when you change from steam to a drm-free version of desura / humble / gog

**Comment by MikeMaximus** [comment]
This is how this feature will work for the upcoming version.

1.  Only Start and End date/time is tracked per game session.  I'll see about adding more data in the future.
2.  Session Tracking is off by default.  There is a new option for Session tracking in Settings.
3.  Added a Session Viewer with simple functions to the Tools menu.
      - You can filter the viewer by game name and date range.
      - You can delete sessions.
4.  Session data is stored locally, it currently does not sync with the backup folder.
